### ISSUE TITLE
Laravel passport

### ISSUE THREAD

**Issue by soumadipshyamm** [jaredhanson/passport#1006]
auth()->guard('admin')->attempt($request->only(['email', 'password']))) 
,.... 
any one tell me, this is support passport or not .
 because  show issue  is 

BadMethodCallException: Method Laravel\Passport\Guards\TokenGuard::attempt does not exist. in file C:\xampp\htdocs\test\passportapi\laravel-backend-api\vendor\laravel\framework\src\Illuminate\Macroable\Traits\Macroable.php on line 112

**Comment by Giviko28** [comment]
Make sure ur guard is defined in auth.php(you could also check ur passport.php config).

**Comment by jaredhanson** [comment]
This project is the Node.js authentication framework, and unrelated to PHP or Laravel. Closing.
