### ISSUE TITLE
Unify the way to access profile picture

### ISSUE THREAD

**Issue by yuri-karadzhov** [jaredhanson/passport#103]
Different strategies store profile picture in different places:

```
profile._json.picture.data.url or profile.photos[0].value - Facebook
profile._json.pictureUrl - LinkedIn
profile._json.picture - Google +
```

It will be much easier to use several strategies if it will be just `profile.picture`

**Comment by sochka** [comment]
Does this even work with Google accounts? For me `profile.photos` returns `undefined`.
