### ISSUE TITLE
Dynamic redirect after successful authentication per request

### ISSUE THREAD

**Issue by miloconway** [jaredhanson/passport#120]
**Use Case**: User has been browsing for a while, then his session expires. The next url he navigates to needs to be authenticated. The backend server renders a login view rather than redirecting to /login. The login page may then capture the user's intended pathname, queries, and hash tags and save it to an input of the login form via javascript. The user is authenticated against the submitted name and password, and if correct, redirected based on the information submitted with the login form. For the end user, there is no need to try to get back to his intended page from the successRedirect url should they be different.

**Comment by peon374** [comment]
I want to be able to use the newly recovered user identity to determine the URL to direct to.

**Comment by manakor** [comment]
@jaredhanson, where's documentation covering `successReturnToOrRedirect` option? Can't find it in the repository overview/[README.md](https://github.com/jaredhanson/passport/blob/master/README.md), neither on the official website…

**Comment by xemasiv** [comment]
I just use sessions instead. Works well at least.

```
  app.get(
    '/auth/google/callback',
    (req, res, next) => {
      if ( eq.get('Referrer').includes('google.com') === false ) {
        req.session["redirect_override"] = req.get('Referrer');
        console.log('Referrer set to:', req.get('Referrer'));
      }
      next();
    },
    passport.authenticate('google'),
    (req, res) => {
      res.redirect(req.session["redirect_override"] || "/");
      req.session["redirect_override"] = "";
    }
  );
```

**Comment by uiteoi** [comment]
@jaredhanson, @matthiasg, @niksumeiko, it would be great indeed to document ```successReturnToOrRedirect``` to also guaranty that accidental code changes will not break this essential but undocumented feature.

**Comment by backpropagation-chesney9** [comment]
https://nodeer.space/questions/nodejs-offers-a-simple-and-effective-way-to-redirect-users-to-another-page-after-they-have
