### ISSUE TITLE
Login session across subdomains

### ISSUE THREAD

**Issue by cailie** [jaredhanson/passport#125]
Hi there,

Does Passport support the sharing of login sessions across applications running on different subdomains?

It appears that setting the cookie domain (in the express session options) is not sufficient to make this work. What I'm finding is that the login session of one application is reset when I navigate to the other, bringing me back to the login form of each.

Advice will be greatly appreciated,
-C

PS. Just commented on issue https://github.com/jaredhanson/passport-local/issues/20, but posting here because this question pertains to passport in general.

**Comment by tnguyen14** [comment]
@cailie is there a way to allow for more than 1 domain, instead of subdomains?

**Comment by rkait** [comment]
@cailie how did you check authentication with your cookie session method? Did you store anything on the `req.session` object? I know that passport stores login information in `req.user` so I am not sure how to manage the session for all subdomains. Thanks for your help!

**Comment by shinux** [comment]
works for me.

**Comment by archiebaer** [comment]
So just confirming, by default, this doesn't allow session cookies to be accessed by subdomains? Because I have a thing where you login, and users can create sites using JS on subdomains, and I was researching if stealing the session cookie was a security concern (https://github.com/go-gitea/gitea/issues/302).

**Comment by devodii** [comment]
does this work for localhost?
