### ISSUE TITLE
passport authenticate with support for XHR

### ISSUE THREAD

**Issue by cultofmetatron** [jaredhanson/passport#126]
I just wrote some code for authenticate that handles xhr

https://gist.github.com/cultofmetatron/5349630

in this day and age, I feel it should be default behavior to have parameters for xhr requests in express. If enough people agree or I have the blessings of the upstream guys, I can go in and try to add such functionality myself.

This is the idea of what Im going for

passport.authenticate('local', {
   successRedirect: '/',
   failureRedirect: '/login',
   successXhr: JSONToSendBack
   failureXhr: JSONToSendifFailure
   failureFlash: true

**Comment by rocketspacer** [comment]
Why isn't this documented?

**Comment by KNClausen** [comment]
This should be documented. Client-side needed to retrieve errors in .json format, so flashes would not work. Fail with error fixed my problem though. Thanks.

**Comment by jwater7** [comment]
+1 I'd love to see this documented too
Someone wrote up an issue for that here: https://github.com/jaredhanson/passport/issues/458

**Comment by kap1147** [comment]
This is still useful in 2021. The API support in passport needs to be updated imo. This soldved my issue with client receiving errors in JSON format.
