### ISSUE TITLE
deserializeUser called 10x

### ISSUE THREAD

**Issue by shauntrennery** [jaredhanson/passport#14]
On login with in my app, I've noticed that deserializeUser is called 10x. Any ideas why this would be the case. 
Any help would be greatly appreciated. 

Thanks

**Comment by Boycce** [comment]
For projects relying on the flexibility of asset directories such as Sails, moving asset routing (`express.static`) to the top slows document responses.
Using Nginx to serve assets is a great alternative.

**Comment by connorblack** [comment]
@Boycce can you provide some more insight into how to handle this for sails?

**Comment by Boycce** [comment]
I just keep the flow of the http config normal, as is. 

*sails.config.http*
```
  middleware: {
    order: [
      'cookieParser',
      'session',
      'passport',
      'passportSession',
      'bodyParser',
      'handleBodyParserError',
      'methodOverride',
      'poweredBy',
      '$custom',
      'router',
      'www',
      'favicon',
      '404',
      '500'
    ]
  }
```

Then when requests are sent to my sever, i route them first through Nginx to sort assets from views/pages via location directives. From this setup, asset requests never hit node, which are the source of the *x10 deserializeUser* issue.

**Comment by MarkoCen** [comment]
FYI, requests failed to find assets would also pass to passport middleware even if using static middleware above.

**Comment by developius** [comment]
Thanks for the fix @jaredhanson, this is really useful as it prevents the calls to mongoose for finding the user - this is ugly in the logs and a pointless overhead 🙈

```
Mongoose: users.findOne({ _id: ObjectId("5904b44a615a277b67c14168") }, { fields: {} })
Mongoose: users.findOne({ _id: ObjectId("5904b44a615a277b67c14168") }, { fields: {} })
Mongoose: users.findOne({ _id: ObjectId("5904b44a615a277b67c14168") }, { fields: {} })
```
