### ISSUE TITLE
Passport.js does not work with cookieSession (Express.js)

### ISSUE THREAD

**Issue by eneko89** [jaredhanson/passport#155]
I'm using Passport to log in with Facebook or Twitter into my service. Since MemoryStore is not intended for production and I'm not going to store much information into the session, I wanted to use cookieSession, but it doesn't work:

```
app.use(express.bodyParser());
app.use(express.methodOverride());
app.use(express.cookieParser());
app.use(express.cookieSession({ secret: 'keyboard cat', cookie: {maxAge: 60 * 60} }));
app.use(passport.initialize());
app.use(passport.session());
app.use(app.router);
```

It works as expected if I repace cookieSession() with session():

```
app.use(express.session({ secret: 'keyboard cat' }));
```

**Comment by AndriesDemeulenaere** [comment]
Did you by any chance resolve this issue, sriram-dev?  I've been stuck on this problem for a while.

**Comment by labcode-de** [comment]
@jaredhanson I think this issue can be marked as closed

**Comment by sasos90** [comment]
I have the problem only when testing with Jest (Supertest agent). Anyone?

**Comment by mitchellporter** [comment]
This still seems to be an issue. Unfortunately I don't have time to isolate and test right now but I don't think this is as simple as trying to write too much data to the cookie. I keep running into an issue where it wants to deserialize the user despite the fact that the user doesn't exist yet. Replacing `cookie-session` with `express-session` fixes the problem. 

Will hopefully have more time to figure out what's wrong soon and then I'll report back.
