### ISSUE TITLE
How to set the session timeout in passportjs?

### ISSUE THREAD

**Issue by jetsonjohn** [jaredhanson/passport#158]
I want to set a session timeout after log in using passportjs. How to set the maxAge for the session using passportjs. What is the default max age for the session that passportjs provide?

**Comment by vebtopalli** [comment]
app.use(function (req, res, next) {
  req.sessionOptions.maxAge = req.session.maxAge || req.sessionOptions.maxAge
  next()
})

Refer to #Per-user sticky max age
https://github.com/expressjs/cookie-session
