### ISSUE TITLE
Multi-strategy authenticate(): specify options per strategy

### ISSUE THREAD

**Issue by thomas-riccardi** [jaredhanson/passport#179]
Currently we can use `authenticate()` with a single strategy name, or an array of strategies names. However the `authenticate()` `options` are global to all the strategies in the array.

It would be great if the strategies array could also be an array of object with a `strategy` key (or `name`) to designate the strategy, and the other keys as options overriding the default options.

Not all options make sense though: `failureRedirect` is only used when all strategies have been tested and failed, so this is not related to a specific strategy.

The use-case is an app with both browser session support for a web app with a strategy with session, and a REST API with localapi, hash or token strategy without session, all on the same route:

``` javascript
app.get('/hello', 
  passport.authenticate([ 'local', { strategy: 'hash', session: false } ]),
  function(req, res) { 
    ... 
  });
```

Currently the only way to do this is to use the `callback` argument of `authenticate()`, and re-implement the logic of the default behavior...

**Comment by redben** [comment]
@triccardi-systran have you managed to find a work around this issue ? I have more or less the same use case, same app exposing an api and browser content (my question on [stackoverflow](http://stackoverflow.com/questions/29446709/using-sessions-on-passportjs-conditionally-depending-on-strategy) )
