### ISSUE TITLE
Custom Authenticate Callback Not Called on Error

### ISSUE THREAD

**Issue by funseiki** [jaredhanson/passport#186]
I posted this on [Stackoverflow](http://stackoverflow.com/q/20206583/865883), but thought I might have more luck here:

I was hoping to utilize the custom callback to handle both successes and failures for logins in Passport's authenticate local strategy, but it looks like it's only called on success.

Here is a snippet of what I'm talking about:

```
passport.use(new LocalStrategy(
    {usernameField: 'email', passwordField: 'password'},
    function(email, password, done) {
        if(canLogin) done(null, user);
        else done({message: "This is an error message" }, false, { message: "Some Info" });
    }
));


app.post('/login', function(req, res, next) {
      passport.authenticate('local', function(err, user, info) {
         // Only called if err is not set
         res.send("Hello");
    });
```

From the client, using a bad input:

`> curl -d "username=bad&password=input" "http://myurl"`
Returns
`> [Object object]`

A 'good' input returns "Hello."

The [docs](http://passportjs.org/guide/authenticate/) imply that passport.authenticate allows the error object to trickle down and be handled by the callback, but the above shows otherwise. Am I interpreting this incorrectly?

**Comment by ibrahimmt** [comment]
app.post('/login', passport.authenticate('login'), function(req, res, next) {
     res.send("Hello");
});

use this code
