### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by JedWatson** [jaredhanson/passport#206]
Hi,

First off, thanks for Passport - it's a great module and I really appreciate the work you've put into it. So please don't hear this as a whinge.

I was just trying to figure out if it's safe to update to 0.2.0, and spent quite a bit of time trawling the commits between versions to figure out what's changed and what I need to do...

It would be really helpful if you could add a CHANGELOG.md file to the project and note changes between versions in it (maybe with notes about why you've moved from 0.1.x to 0.2.x) so projects depending on it can more easily be adapted to use new features or APIs, as well as planning to refactor out deprecated / removed ones.

I do this for my own modules by skimming through the commits between releases and listing the major updates, and have found it a really valuable process.

Thanks,
Jed.

**Comment by simison** [comment]
Changelog now exists. Thanks! 🎉   https://github.com/jaredhanson/passport/blob/ff4450692b4fbc62b8f425a70299571158281a16/CHANGELOG.md
