### ISSUE TITLE
req.isAuthenticated fails on successRedirect

### ISSUE THREAD

**Issue by bitpshr** [jaredhanson/passport#210]
I set up a very basic express application that has two views: **login** and **create**. When a user tries to navigate to the "create" page and they are not authenticated, I redirect them to the "login" page, then back to the "create" page after authing with Twitter.

**The issue** is that redirecting to `/create` on `successRedirect` in turn redirects back to `/login` because `req.isAuthenticated()` fails on the call to `ensureAuthenticated`. Why?

``` javascript
 // ...
app.get('/login', views.login);
app.get('/create', ensureAuthenticated, views.create);

app.get('/auth/twitter', passport.authenticate('twitter'), function (req, res) { });
app.get('/auth/twitter/callback', passport.authenticate('twitter', {
    successRedirect: '/create',
    failureRedirect: '/'
}));

function ensureAuthenticated(req, res, next) {
    if (req.isAuthenticated()) { return next(); }
    res.redirect('/login');
}

http.createServer(app).listen(app.get('port'), function () {
    console.log('Express server listening on port ' + app.get('port'));
});
```

_Note:_ I have sessions properly configured:

```
app.use(express.session({ secret: 'lolomg1337' }));
app.use(passport.initialize());
app.use(passport.session());
```

**Comment by demisx** [comment]
It appears that `isAuthenticated()` can only be used if session is enabled. Please correct me if I am wrong.
