### ISSUE TITLE
req.logout doesn't remove session in sessionStore with connect-redis

### ISSUE THREAD

**Issue by 2fours** [jaredhanson/passport#216]
I'm using passport-local. I have a logout method that calls req.logout to end the session. The problem is it doesn't clear req.session so connect saves a bogus session entry to redis when req.send is called:

Before logout:
1) "{\"cookie\":{\"originalMaxAge\":259200000,\"expires\":\"2014-03-21T22:03:55.265Z\",\"httpOnly\":true,\"path\":\"/\"},\"passport\":{\"user\":\"bn\"}}"

After logout:
1) "{\"cookie\":{\"originalMaxAge\":259200000,\"expires\":\"2014-03-21T22:04:01.148Z\",\"httpOnly\":true,\"path\":\"/\"},\"passport\":{}}"

Is this something we're expected to take care of ourselves?

**Comment by doublerebel** [comment]
I took a look at this and #246 today.  I've traced the calls while monitoring Redis, and the **express-session** API has changed since the middle of this issue timeline.

expressjs/session#50 (2014 June 14) added a new `unset` option, where the session will be destroyed during `res.end`.  RedisStore must be initialized with option `unset: "destroy"` and `res.session` must be `null` :
https://github.com/expressjs/session/blob/cd6b0879af2792aeb832bf072dd73327f54adde6/index.js#L242

**passport** does remove the user information after logout, I think the `unset` solution from **express-session** to clean up at the end of the response is sensible.

**Comment by kevinSuttle** [comment]
Wondering about this myself. Maybe just a documentation issue like others have mentioned.

**Comment by jayfresh** [comment]
I've just come across this with the same problem. I'd be happy for a documentation change to be made.

**Comment by AishwaryaSivaraman** [comment]
I have come across the same problem, is there anyway to delete the session on logout?

**Comment by phagunbaya** [comment]
Any further update guys ?? I'm using this :
```
request.session.destroy()
```

This does clear session for me.

**Comment by Vadorequest** [comment]
I'm in a case where I want to destroy another session. How can I do that? I don't find any doc.

For the story, I'm implementing a "max sessions limit" which automatically deletes the oldest session, which won't be the current session. Maybe giving an ID will do the trick but the lack of docs (or my unability to find them) sucks.

**Comment by Vadorequest** [comment]
Well, I actually just found it in the doc. https://github.com/expressjs/session#storedestroysid-callback

Gonna give it a try.

**Comment by knoxcard** [comment]
Guys, take a look at this, I coded a redis function to manually destroy the session but found out today that I could remove it and just set this under Session.


unset

Control the result of unsetting req.session (through delete, setting to null, etc.).

The default value is 'keep'.

https://github.com/expressjs/session
'destroy' The session will be destroyed (deleted) when the response ends.
'keep' The session in the store will be kept, but modifications made during the request are ignored and not saved.

**Comment by knoxcard** [comment]
```
  const express_session = require('express-session'),
    RedisStore = require('connect-redis')(express_session)
  app.set('redis_store', new RedisStore({
    client: new Redis({
      db: 5
    }),
    ttl: 60 * process.env.session_exp_mins
  }))
  app.set('session_vars', {
    prefix: process.env.session_prefix,
    secret: process.env.session_secret,
    name: process.env.session_name,
    store: app.get('redis_store'),
    rolling: true,
    saveUninitialized: true,
    unset: 'destroy',
    resave: true,
    proxy: process.env.protocol === 'https',
    logErrors: process.env.debug === 'true',
    cookie: {
      path: '/',
      domain: '.' + process.env.app_domain,
      secure: process.env.protocol === 'https',
      maxAge: 60000 * process.env.session_exp_mins,
      httpOnly: true,
      expires: false
    }
  })
  app.set('session', express_session(app.get('session_vars')))
  app.use(app.get('session'))
```
