### ISSUE TITLE
Support for Express 4?

### ISSUE THREAD

**Issue by jgallen23** [jaredhanson/passport#222]
Has anybody had any success using passport with Express 4?

**Comment by framerate** [comment]
@zachcowell thanks for that.

I wasn't using passport.session() in express 3 and I'm not sure why, but that line was the missing piece.

**Comment by nemanjavuk** [comment]
I'm not sure if anybody is still having issues with this but I'm having problems. req.session.passport and req.user are always empty and neither serializeUser nor deseiralizeUser aren't being called. I'm using the latest express 4.11.2, express-session 1.10.2, body-parser 1.11.0, passport 0.2.1 and passport-local 1.0.0 with mysql as a backend.
I'm setting up the express and passport like this:
```
var bodyParser = require('body-parser');
var session = require('express-session');
var MemoryStore = session.MemoryStore;
var _ = require('underscore');
var passport = require('passport');

app.use(bodyParser.json());
app.use(bodyParser.urlencoded({extended: true}));
app.use(session({
    key: 'KEY',
    secret: 'SECRET331156%^!fafsdaasd',
    store: new MemoryStore({reapInterval: 60000 * 10}),
    saveUninitialized: true,
    resave: false
}));
app.use(passport.initialize());
app.use(passport.session());
require('./config/passport')(passport); // pass passport for configuration
```
Authentication strategies:
```
module.exports = function (passport) {
    passport.serializeUser(function (user, done) {
        logger.info('SERIALIZE USER');
        done(null, user.id);
    });

    passport.deserializeUser(function (id, done) {
        logger.info('DESEIRALIZE USER!');
        mysqllib.getConnection(function (err, connection) {
            if (err) {
                done(err);
            }
            var sql = "SELECT * FROM users WHERE idusers = ?";
            logger.info('sql: ' + sql);
            connection.query(sql, [id], function (err, rows) {
                connection.release();
                var user = {};
                user.id = rows[0].idusers;
                done(err, user.id);
            });
        });
    });

    passport.use('local-signup', new LocalStrategy({
            usernameField: 'email',
            passwordField: 'password',
            passReqToCallback: true // allows us to pass back the entire request to the callback
        },
        function (req, email, password, done) {
            logger.info('CALLING local-signup');
            var firstname = req.body.firstname;
            var lastname = req.body.lastname;
            var role = req.body.role;
            mysqllib.getConnection(function (err, connection) {
                var sql = "INSERT INTO users VALUES(0, ?, ?, ?, ?, null, ?, 0, null, null, null, null, null, null, 0, 0)";
                logger.info('sql: ' + sql);
                connection.query(sql, [email, password, firstname, lastname, role], function (err, rows) {
                    connection.release();
                    if (err) {
                        if (err.code == 'ER_DUP_ENTRY') {
                            logger.info('er_dup_entry');
                            return done(err);
                        } else {
                            logger.info('general err');
                            return done(err);
                        }
                    } else {
                        logger.info('everything is OK!');
                        var user = {};
                        user.id = rows.insertId;
                        req.session.user_auth = user.id;
                        return done(null, user);
                    }
                });
            });
        }));

    passport.use(
        'local-login',
        new LocalStrategy({
                usernameField: 'email',
                passwordField: 'password',
                passReqToCallback: true // allows us to pass back the entire request to the callback
            },
            function (req, email, password, done) { 
                mysqllib.getConnection(function (err, connection) {
                    if (err) {
                        logger.info('getConnection: ' + err);
                        return done(err);
                    }
                    var sql = "SELECT idusers, first_name, last_name, email, phone, dob, address, role, photo1, photo2, photo3, photo4, phonevalidated, uservalidated FROM users WHERE email = " + connection.escape(email) + " AND password = " + connection.escape(password);
                    connection.query(sql, function (err, rows) {
                        connection.release();
                        if (err) {
                            logger.error("select user", err);
                            return done(err);
                        } else if (rows.length) {
                            var user = rows[0];
                            user.id = rows[0].idusers;
                            return done(null, user);
                        } else {
                            logger.warn('Incorrect Login credentials, username: ' + email + ' password: ' + password);
                            return done(null, false, {message: 'unauthorized'});
                        }
                    });
                });
            })
    );
};
```
How I use a strategy in an express route:
```
app.post('/login', function (req, res, next) {
    passport.authenticate('local-login', function (err, user, info) {
        if (err) {
            mysend(res, 500, 'Ups. Something broke!');
        } else if (info) {
            mysend(res, 401, 'unauthorized');
        } else {
            mysend(res, 200, JSON.stringify(user));
            logger.info(req.user);
            logger.info(req.session);
        }
    })(req, res, next);
});
```
Everything works fine except the serializeUser and deserializeUser that aren't being called. I can even manually set a value in a session inside a strategy but I don't want to do that. I want passport to handle sessions.

**Comment by framerate** [comment]
@nemanjavuk it's likely you either are missing middleware or have it in the wrong order..

Here's mine:

```
app.use(serveStatic(__dirname + '/static', {'index':false}));
app.use(session(sessionConfig));
app.use(passport.initialize());
app.use(passport.session());
app.use(csrf());
app.use(bodyParser.urlencoded({ extended: false }));
app.use(bodyParser.json());
app.use(debugOutput);
```

Compare with yours?

**Comment by nemanjavuk** [comment]
@framerate As far as I can see the only difference is that you use bodyParser after the express and passport sessions but I do it before. I tried with your approach but it doesn't work either way.

**Comment by darth-cheney** [comment]
@nemanjavuk Did you ever find a solution? I'm having precisely the same problem. Neither `serializeUser` nor `deserializeUser` are even being called during the authentication process. All middleware seems to be loaded in the correct order too.

**Comment by nemanjavuk** [comment]
@darth-cheney As a matter of fact I have. I was missing to call req.login() in my custom callback which in fact calls serializeUser:

```javascript
app.post('/login', function (req, res, next) {
    passport.authenticate('local-login', function (err, user, info) {
        if (err) {
            mysend(res, 500, 'Ups. Something broke!');
        } else if (info) {
            mysend(res, 401, 'unauthorized');
        } else {
            req.login(user, function(err) {
                if (err) {
                    mysend(res, 500, 'Ups.');
                } else {
                    mysend(res, 200, JSON.stringify(user));
                }
            }
        }
    })(req, res, next);
});
```

Hope it helps

**Comment by beaugunderson** [comment]
Noting that I too had many of these problems; my issue was that I was using MemoryStore. I switched to connect-redis RedisStore /w redis-url and they all went away. :)

**Comment by BarthesSimpson** [comment]
I had the same issue with my serializeUser and deserializeUser functions never being called. My educated guess is that passport.authenticate('local') was causing the glitch in my middleware, because everything worked after I replaced that with a custom function as follows:

Instead of:

    app.get(/^(.+)$/, passport.authenticate('local'), function(req, res){
        res.sendFile(__dirname + '/public/'+req.params[0]);
    });

I used: 

    app.get(/^(.+)$/, ensureAuthenticated, function(req, res){
        res.sendFile(__dirname + '/public/'+req.params[0]);
    });

    function ensureAuthenticated(req, res, next) {  
      if (req.isAuthenticated()) { 
    console.log('user logged in '+ req.user.username);
        next(); 
      } 
      else {   
        console.log('user not logged in '+ req.user);
        res.redirect('/login');          
      };
};

**Comment by ORESoftware** [comment]
@Shershnev-AV thank you SOOOOO much for your answer, that is correct. I had the common problem that my serializeUser and deserializeUser callbacks were not being fired. It was because I was using the less common scenario that Shershnev-AV described `(passport.authenticate('local', function (err, user, info){})` . Jared Hannson, take note. You are not documenting your software well enough.

**Comment by ORESoftware** [comment]
@larissaleite, @Shershnev-AV 's answer above might solve your problem as I had the same problem as you

**Comment by jaredhanson** [comment]
> Jared Hannson, take note. You are not documenting your software well enough.

@ORESoftware Hopefully you find it good enough for the price I charge for the software.

**Comment by mercmobily** [comment]
@ORESoftware  @jaredhanson  Jared, thank you for your fantastic efforts with Passport and thank you for continuously going through the issue list and never abandon this module.

**Comment by BarthesSimpson** [comment]
Here, here. Passport is epic.

**Comment by simonbogarde** [comment]
I generated my project with the Yeoman fullstack generator and didn't know how to apply @Shershnev-AV 's fix. However, @Awk34 has a nice solution here: https://github.com/Awk34/aksite. 
He extended auth.service with a function called "appendUser" that acts as a middleware and adds the current user to the request.

**Comment by khrykin** [comment]
In my case, `deserializeUser` is called ONLY in Safari and not in Chrome, Firefox etc... So, in Safari  `req.user` exists after page refresh, but in other browsers not. Just can't figure out why... I'm using `postgres` as session storage and `sequelize-passport-local` for retrieving user record. Here is my setup:

```javascript

app.use(bodyParser.urlencoded({
  extended: true
}));
app.use(bodyParser.json({
  extended: true
}));

app.use(session({
  store: new SequelizeStore({
    db: sequelize
  }),
  secret: SESSION_SECRET,
  resave: false,
  saveUninitialized: false,
  cookie: {
    maxAge: 30 * 24 * 60 * 60 * 1000,
   }
}));

app.use(passport.initialize());
app.use(passport.session());

passport.use(User.createStrategy()); // sequelize-passport-local
passport.serializeUser(User.serializeUser()); // sequelize-passport-local
passport.deserializeUser(User.deserializeUser()); // sequelize-passport-local

passport.deserializeUser(function(id, done) {
  console.log("DESERIALIZE");
  console.log(id);
});

app.post('/login', (req, res, next) => {
  passport.authenticate('local', (err, user, info) => {
    if (err) {
      return next(err);
    }
    if (! user) {
      return res.json({ error: info.message }); // Don't want 401 here
    }
    req.logIn(user, function(err){
      if(err){
        return next(err);
      }
      let {id, name, email, picture } = user;
      res.json({id, name, email, picture });
      return next();
    });

  })(req, res, next);

});

```
`"DESERIALIZE"` never prints in Chrome, Firefox, but always does in Safari (as expected).
Any help please, the above solutions seem to not work for me, just have killed the whole day with this issue.

**Comment by choonkending** [comment]
@khrykin Did you ever find out what the cause of your issue was? I am encountering the same issue (working on safari but not chrome), and have tried the above solutions as well, to no avail :(

I do not think `passport` is causing this though, but just wondering whether you found a fix for yours. My hunch is that `express-session` is causing this. :(

**Comment by khrykin** [comment]
@choonkending Yes, I did, my apologies for not posting it here. I used [fetch](https://github.com/github/fetch) to make login request and without setting `{ credentials: 'same-origin' }` option, cookies were not sent to the server (expected behavior as by fetch's documentation) BUT excluding safari, which sends cookies anyway (unfortunately for me because I actually set credentials option, but did it with typo, and had hard times trying to debug this... NUFF SAID). 
So anyway, the problem is likely hides in the way you send requests from client.

**Comment by choonkending** [comment]
@khrykin Legend! This kept me up several nights. Thanks mate.

**Comment by sumitkm** [comment]
@nemanjavuk You are a legend! I have been going round in circles for almost a week now! Thanks for the tip about calling req.login, though I am not sure why I had to do it and why passport-local-mongoose wasn't doing it by itself. I'll continue with that research (its probably a pbkac error ;-)...), but for now, my sessions have the user associated woo hoo!!! Thank you!

**Comment by BenTsai85** [comment]
I had the same problem as mentioned, deserializeUser is never called. But I found that findById is a Promise and will never be resolved...
```
User.findById(id, function(err, user) {
            console.log(user);
            done(err, user);
        });
```
So if you have the same problem as me using findById, use the following code instead:
```
    passport.deserializeUser( async(id, done) => {
        console.log("deserialize");
        User.findById(id)
            .then( user => {
                console.log(user);
                done(null, user);
            })
            .catch( err => {
                console.error(err);
                done(err);
            });
    });
```

**Comment by Aaronius** [comment]
@khrykin I just spent a good 5 hours trying to figure this out. Thank you!

**Comment by rohanparmar27** [comment]
passport.deserializeUser((id, done) => {
    User.findById(id).then(user => {
      if (_.isEmpty(user))
        throw new Error(`user not found`)
      done(null, user.toJSON());
    }).catch(e => {
      done(e)
    })
  });

@BenTsai85 u can set it and try

**Comment by thomasgauvin** [comment]
@zachcowell thank you for sharing this, I was getting issues with Passport returning Bad Request with no helpful errors logs, your post shed light into the cookie: { secure: true } setting that I had, which was causing the issue
