### ISSUE TITLE
Redirect not working in Express 4

### ISSUE THREAD

**Issue by giacomorebonato** [jaredhanson/passport#233]
I'm doing some test in Express 4 and Passport with Facebook authentication.
It seems like the redirect to Facebook doesn't work and the request goes timeout.

**Comment by PrimeLens** [comment]
same as above, doesn't redirect, just logs the user and waits.

**Comment by PrimeLens** [comment]
aaaah,  I think I see whats wrong, there is a mistake in the docs.  Under Authenticate
http://passportjs.org/guide/authenticate/
the last code block for custom callback
it should say app.post not app.get
If I change it and use this custom callback technique of wrapping passport.authenticate in an anon function to pass in req, res, next
and use it for app.post then it works
