### ISSUE TITLE
Creates cookie when not logged in

### ISSUE THREAD

**Issue by tirithen** [jaredhanson/passport#259]
Express session module recently added the option saveUninitialized to prevent the creation of cookies if the session is empty. This is handy for following laws about not creating cookies if the user has not accepted the use of cookies.

It works fine on a plain express project, but in a project where I use this fantastic library the cookie gets created even when I set saveUninitialized to false.

For more details se express session module documentation: https://github.com/expressjs/session#options

**Comment by doublerebel** [comment]
+1

**Comment by ashelley** [comment]
Hello,

I've created the following patch that addresses this issue.  My problem was that redis was getting filled up with unneeded keys on api requests that did not require a session at all. 

https://github.com/jaredhanson/passport/pull/320

There may be implications downstream but i fixed up the existing tests and it seems okay.

Hope this helps,

-Adam

**Comment by mountHouli** [comment]
+1

**Comment by vclteam** [comment]
+1
any workaround?

**Comment by jaredhanson** [comment]
Fixed by merging #320. Published to npm as passport 0.3.0.
