### ISSUE TITLE
Authenticate should set the req.user if successful

### ISSUE THREAD

**Issue by mwawrusch** [jaredhanson/passport#3]
Hi Jared, I stumbled upon a little problem. I have this code here:

```
@app.post "/sessions", @passport.authenticate("local", failureRedirect: "/sessions/login"), (req, res) ->
    res.redirect @sessionRoutesPathHelper.profile(req.user.username)
```

which, upon successful authentication should redirect to the users profile page. This does not work though as the user object in req is only set in the next request, after the redirect. 

I think it would be a good idea to set req.user to the user in authenticate before invoking the callback

**Comment by shoaibnoor95** [comment]
router.post("/signup",function(req, res, next) {

  var username = req.body.username;
  var phoneNumber = req.body.phoneNumber;
  var email = req.body.email;
  User.findOne({ $or: [{ username: username }, { email: email }, { phone_Number: phoneNumber }] }, function (err, user) {

    if (err) { return next(err); }
    if (user) {
      return res.send({message:"User already exists"});   
    }
    var password = req.body.password;
    var newUser = new User({
      username: username,
      email: email,
      phone_Number: phoneNumber,
      password: password,
    });
    newUser.save(next);
    var token = new Token({
      _userId: newUser._id,
      token: crypto.randomBytes(16).toString('hex')
    });
    token.save(next);
    var transport = nodemailer.createTransport({
      service: 'gmail',
      auth: {
        user: 'mail.shoaib95@gmail.com',
        pass: 'n0kia5130'
      }
    });

    ejs.renderFile(__dirname + '/templates/template.ejs', (err, data) => {
      
      if (err) {
        console.log(err.name + " " + err.message);
        console.log('if')
      }
      else {
        console.log('else')
        var options = {
          auth: {
            api_user: '',
            api_key: ''
          }
        }
        var client = nodemailer.createTransport(sgTransport(options));
        var email = {
          from: '<no-reply>@com',
          to: '@hotmail.com',
          subject: 'Email confirmation for tutorns account',
          html: data
        };
      
      client.sendMail(email, function(err, info){
        if (err){
          return res.send({message:err.message})
        }
        else{
         return res.send({success:true})
        } 
      })


      }
    })

  }),passport.authenticate('local-login',function (err, user, message){
  console.log('here');
  if (err) {
    console.log('here1');
  return res.send(err.message)
  }
  if (user) {
    req.logIn(user, loginErr => {
      if(loginErr) {
        console.log(loginErr)
        return res.json({ success: false, message: loginErr })
      }
         console.log(user)  
        return res.send({user:user}); 
  })
}
   
})(req, res, next)
})
else
[1] here
[1] _http_outgoing.js:494
[1]     throw new Error('Can\'t set headers after they are sent.');
[1]     ^
[1]
[1] Error: Can't set headers after they are sent.
[1]     at validateHeader (_http_outgoing.js:494:11)
[1]     at ServerResponse.setHeader (_http_outgoing.js:501:3)
[1]     at ServerResponse.header (D:\Codes\13-5-18\node_modules\express\lib\response.js:767:10)
[1]     at ServerResponse.send (D:\Codes\13-5-18\node_modules\express\lib\response.js:170:12)
[1]     at ServerResponse.json (D:\Codes\13-5-18\node_modules\express\lib\response.js:267:15)
[1]     at ServerResponse.send (D:\Codes\13-5-18\node_modules\express\lib\response.js:158:21)
could please someone tell me what``s the reason of getting this error
