### ISSUE TITLE
State of passport

### ISSUE THREAD

**Issue by bryangarza** [jaredhanson/passport#313]
@jaredhanson wondering what your plan is for Passport in the future, since there hasn't been a commit in 4 months but a lot of open issues and PRs. Have you considered looking for a maintainer? I'm sure people are willing to take up the project and keep working on it.

**Comment by Magnitus-** [comment]
To echo Bryan's concerns: 

While Passport looks like a mature, well thought of, popular solution, I'm going with a home-made solution instead of Passport because of personal concerns for the future of the project.

While it doesn't really affect me at this point, but it seems like a lot of efforts and thoughts went into this project. Hopefully, it that won't end up being in vain due to a lack of maintenance.

**Comment by Windsock** [comment]
A day ago, jaredhanson replied to a thread about forking and handing over ownership to other contributors: https://github.com/jaredhanson/oauth2orize/issues/108#issuecomment-71382875
I hope regular maintenance returns to this project, would hate to have to try implementing my own authorization just out of lack of maintenance with this.

**Comment by Nijikokun** [comment]
I'm in favor of @jaredhanson bringing on some core maintainers that will allow this to flourish and moving it over to an organization.

**Comment by jaredhanson** [comment]
Closing this since there's nothing actionable.  I'm in the process of reviewing pull requests now, please comment on any that are specifically relevant to issues or concerns that you have.  Thanks!

**Comment by Nijikokun** [comment]
> Closing this since there's nothing actionable. I'm in the process of reviewing pull requests now, please comment on any that are specifically relevant to issues or concerns that you have. Thanks!

Perhaps we should make a community organization rather than wait for you to be available all the time.

**Comment by jaredhanson** [comment]
I'll take that under consideration.  First I would need to find regular contributors who I believe understand the philosophy behind Passport and would maintain it with that integrity.  Right now, that's just me (and maybe one other person who I have not asked if they want the responsibility).  If anyone else wants the responsibility, they are encouraged to submit quality pull requests.

I would be interested in handing over maintenance of some of the strategies before the core passport module itself.
