### ISSUE TITLE
How to use it without any express framework?

### ISSUE THREAD

**Issue by totty90** [jaredhanson/passport#321]
How to use without all the sugar? I need it raw.

**Comment by Windsock** [comment]
Passport is a Node middleware so it should be possible by looking at its source code which seems to be well documented and working its API into your own middleware.

**Comment by totty90** [comment]
Ok, thanks...

**Comment by Windsock** [comment]
There is definitely a lack of true API documentation currently, although the source code itself does seem to be well-commented as well. I do hope some better documentation can be made soon.

**Comment by totty90** [comment]
Documentation can warn me of really big mistakes/pitfalls. Source code alone will not do that. That's why I prefer real docs.

**Comment by jaredhanson** [comment]
No apologies, this is free code.  Closing since this doesn't raise a functional issue.  If you write any docs, I'd be happy to link to them in the wiki or merge them if they are API docs.
