### ISSUE TITLE
Do this repository is up to date ?

### ISSUE THREAD

**Issue by florian-rossiaud** [jaredhanson/passport#328]
Hi,

I would to know if this repository is still up to date. Because I'm seeing that a lot of repo from jarehason passport are dead (no commit, nothing) since at least six month.

I got some problems with strategy like google but nothing is moving on.

What is going on ?

**Comment by florian-rossiaud** [comment]
@jaredhanson

**Comment by jaredhanson** [comment]
Yes, this repository is up to date.  Some strategies are not, such as Google, as you mention.  I'm working to get those up to date as well.  Please comment on the relevant strategies if you have concerns, not the core module.  Thanks.

**Comment by florian-rossiaud** [comment]
I leave this message because on your google repository some people are waiting some news from you (like this issue : https://github.com/jaredhanson/passport-google-oauth/issues/56).

If you need help to maintain some repository by yourself, you can still ask to the community to help you.

Regards,

**Comment by tellnes** [comment]
I also would like to point out that [passport-facebook](https://github.com/jaredhanson/passport-facebook) deserves some love.

And please add some maintainers. I don't care who, just someone who is active and have commit bits. If you want to reserve the rights to publish to npm, that's fine.

**Comment by fiznool** [comment]
:+1: on adding maintainers. I'm happy to help out.

**Comment by jaredhanson** [comment]
The requirement for becoming a maintainer is first submitting quality patches.
