### ISSUE TITLE
automatically logoff after few requests

### ISSUE THREAD

**Issue by CrackerakiUA** [jaredhanson/passport#333]
Well i have simple form which check if username exists in users.

app.post('/api/checkUsernameAvail', function(req, res) {
    console.log(req.user);
    if(req.isAuthenticated()){
        User.find(
        {username: req.body.username.toLowerCase()},function(err, user){
            if(user.length==0) var avail=true;
            else var avail=false;
            res.send(avail);
        });
    }else{
        res.send(false);
    }
});
After few requests, each time different count and different timeout, user automatically logged off. Not sure why, perhaps passport do something, but i am not sure how to fix this task. Have tried to not user req.isAuthenticated(), same result.

**Comment by jaredhanson** [comment]
I'm not seeing any lead that suggests this is a issue with Passport.  Closing.  Re-open if you can point to a specific issue with this project.
