### ISSUE TITLE
Not using sessions, but it's still trying to serialize user

### ISSUE THREAD

**Issue by akuz** [jaredhanson/passport#349]
I am not using express sessions at all (I provide by own durable token to the user and don't keep any session on the server). However, passport is still trying to serialise user. It complains unable to serialise user into session. I am using passport-facebook and passport-twitter. Both of them produce the same "unable to serialize user into session" error. The documentation says that the use of sessions is optional, but what I see is that passport is unable to work without sessions at all... Please help.

**Comment by doowb** [comment]
When using `passport.authenticate` middleware are you passing `{session: false}` in the `options`?

**Comment by akuz** [comment]
Nope, sorry I missed that in the documentation. I see it now. I just assumed from other parts of the documentation that sessions are optional, and therefore everything should just work without them. Maybe it would be worth changing the docs to say "sessions can optionally be disabled" :) I am sure it should work now. (Can only try later.)

P.S. Off topic: do you know why passport-twitter requires sessions? It complains that OAuth (I assume 1.0) requires sessions...

**Comment by doowb** [comment]
> Off topic: do you know why passport-twitter requires sessions?

No idea. Might want to ask on that repo.

**Comment by tbjers** [comment]
Passport-twitter requires sessions because it needs to save tokens between
requests and redirects through the OAuth flow. See this diagram:
http://oauth.net/core/diagram.png

**Comment by akuz** [comment]
Thanks so much!

**Comment by akuz** [comment]
There is one problem with using sessions I see... If I have several load balanced services, the return redirect from Twitter may potentially hit another server, which won't have the session... Of course, this could be solved by some a centralized session store, but this is exactly the problem I was trying to avoid... As I've read on the internet, it seems possible that Twitter OAuth flow doesn't actually require sessions (the secret can be appended dynamically to the callback URL). Do you know any session-less implementations of Twitter auth? Thanks!

**Comment by tbjers** [comment]
You'd have to store it somewhere. Database or elsewhere. Or set sticky
sessions in your load balancer.
