### ISSUE TITLE
New site breaks non-JS browsers

### ISSUE THREAD

**Issue by joepie91** [jaredhanson/passport#353]
Upon finding that the site for Passport had changed significantly, and that it used a lot of fancy JS "enhancements", I decided to have a look at how well it functioned without JS. As it turns out, it doesn't, *at all*.

The "view strategies" button is completely broken. "Section jumping" in the documentation is completely broken. Neither of these are functionality that absolutely *requires* JS. Whatever happened to the practice of progressive enhancement?

Documentation should really be available to anybody with a web browser (and, ideally, even to people *without* a web browser). There are many people who either cannot enable JS in their browser, do not *want* to enable JS in their browser (eg. for security reasons), or who recursively download a site because their internet connection is unreliable/limited.

The current site breaks all of these usecases, and that should really be fixed.

**Comment by jaredhanson** [comment]
Issues with the website do not affect the Node.js module itself, and should be filed on the relevant GitHub project: https://github.com/passport/www.passportjs.org

The redesign has just launched, so I'm sure there are things that may need to be fixed or revised.  When filing issues for things that are not working correctly, please indicate which browser and device you are using as well as what behavior you expected.

Pull requests that improve progressive enhancement and accessibility are greatly welcome!

**Comment by joepie91** [comment]
Aha. I was looking for the website repo, but couldn't find it - it doesn't seem to be linked from the (new) site anywhere. I'll re-file there.
