### ISSUE TITLE
Logout all other authenticated user's sessions

### ISSUE THREAD

**Issue by juuxstar** [jaredhanson/passport#361]
I'm trying to implement restricting a user to a single session.  Anybody know if there's an easy way in PassportJS to destroy previous sessions registered with the current user?

**Comment by jaredhanson** [comment]
Closing.  This is outside of the scope of this project, which is concerned with authentication only.  Any authorization decisions, including restrictions multiple simultaneous sessions, are application-level concerns.

**Comment by richlewis14** [comment]
Is this still the case ^^. Are there strategies available that will allow us to have a user only have one session.. So prevent the same login details being used across multiple devices. Thanks
