### ISSUE TITLE
Route with passport.authenticate results in bad request

### ISSUE THREAD

**Issue by tleunen** [jaredhanson/passport#371]
I'm using passportjs with expressjs 4.12 and I'm having a bad request when trying to limit access to a route.

The following code gives a bad request
```javascript
router.get('/users', passport.authenticate('local'), function(req, res) {
        res.json({ currentUser: req.user });
});
```
But this one works and gives me the logged in user.
```javascript
router.get('/users', function(req, res) {
        res.json({ currentUser: req.user });
});
```

What could be wrong in the setup? The login system seems to work, the user is saved in the request session, the serialize/deserialize function from passport are called when executing the second code (without the access check).

**Comment by tleunen** [comment]
The doc says: 
> In a typical web application, the credentials used to authenticate a user will only be transmitted during the login request. If authentication succeeds, a session will be established and maintained via a cookie set in the user's browser.

I can see in the request that the cookie is sent.

Could be something with the Local strategy? The code there seems to only check the username/password from the request. But the request is always empty.

**Comment by tleunen** [comment]
The `passport-local` example helped me find my error: https://github.com/jaredhanson/passport/blob/master/test/strategies/session.test.js

I has to use `req.isAuthenticated()` to check if the user was auth. Not make a call to `passport.authenticate('local')`.

**Comment by runemadsen** [comment]
I'm running into the same problem. The passport-local documentation specifically states that you should use `passport.authenticate('local')`, but I'm just getting `Bad Request`. Any tips?

**Comment by hamzapurra** [comment]
`app.post('/login', (req, res) => passport.authenticate('local', {
  successRedirect: '/',
  failureRedirect: '/login',
})(req, res));`

**Comment by Blackbaud-SteveBrush** [comment]
It'd be helpful if this caveat was documented on passportjs.org. Would've saved a few hours of stress :)

**Comment by hudsonpereira** [comment]
Most of the problem i get was because the lib never mention body-parser as a dependency.

**Comment by akohout** [comment]
For me the trick with process.nextTick worked

**Comment by m-adil** [comment]
I'm still facing the same error of **Bad Request**. 
@hudsonpereira I'm not sure but i don't think body-parser is a dependency for passportjs. Added body-parser to test it out but still no progress.

**Comment by rokit** [comment]
I also needed body-parser with `app.post`. Post arguments are sent via the body, ie. `req.body`.

```
var bodyParser = require('body-parser');
app.use(bodyParser.json()); // support json encoded bodies
app.use(bodyParser.urlencoded({ extended: true })); // support encoded bodies
```

**Comment by Logic-Bits** [comment]
@rokit thanks man. The extended did the trick for me. Now it works with Postman.

**Comment by te-online** [comment]
passport.authenticate could really use a parameter to enable debug-logging. It's like a blackbox, and even though I know the dependencies for passport, there is no error in the console when I accidentally forgot something...

**Comment by Kudratov** [comment]
https://github.com/jaredhanson/passport/issues/679
similar problem 
can you help?

**Comment by Jyosiva** [comment]
Hi facing bad request error while registering a new user like below
```
user.register(newuser,req.body.pass,function(err,user){
    if(err)

    {
        console.log(err);
        return res.render('register');
    }   
    //console.log("inside post register");
    passport.authenticate("local")(req,res,function(){
        //console.log("inside passport authenticate");
        res.render('/campground');
    });
```
pls help...

**Comment by jdecuirm** [comment]
passport expects that in the form the names of username and password are those like that username and password, you are using pass for password, change the name in the html attributes.

**Comment by sangeet** [comment]
I am just going to leave this blog post here for anyone who is getting random errors and is unable to figure out how to debug : https://dmitryrogozhny.com/blog/easy-way-to-debug-passport-authentication-in-express

I wasted hours before I could try and figure out what that `"Bad Request"` corresponds to. It was `'Missing credentials'` in my case which was because the body parser was not configured properly.

Adding the line `app.use(express.json())` to my middleware fixed the problem for me, but this blog post hopefully will help others who are stuck in the crappy undescriptive message of 11 characters i.e `"Bad Request"` which really doesn't tell anything.

Just replace your `passport.authenticate('local')` with the following:

```
function (req, res, next) {
    // call passport authentication passing the "local" strategy name and a callback function
    passport.authenticate('local', function (error, user, info) {
      // this will execute in any case, even if a passport strategy will find an error
      // log everything to console
      console.log(error);
      console.log(user);
      console.log(info);

      if (error) {
        res.status(401).send(error);
      } else if (!user) {
        res.status(401).send(info);
      } else {
        next();
      }

      res.status(401).send(info);
    })(req, res);
  },
```
There seriously needs to be a better error message for a library such widely used.

**Comment by joshirj21** [comment]
passport.authenticate("local") fetches username and password from the view engine.Try naming them username and password in the login form.

**Comment by Deepanshu088** [comment]
I am having the same `bad request` issue. Can someone help me by sending the appropriate code? It will be very helpful. It's been two days now, and I couldn't solve the problem yet. Some help will be very useful.

**Comment by sangeet** [comment]
@Deepanshu088 

1. You can follow the steps that I mentioned above, this helped me determine and fix my problem : https://github.com/jaredhanson/passport/issues/371#issuecomment-513893423

2. There is an undocumented `failWithError` option that you can use that might help determine the problem : https://github.com/jaredhanson/passport/issues/458#issue-131801590

Few things to check:

- Is your username and password variable the same as the one specifieid in usernameField and passwordField? What are your username and password variable.

- Can you check if your body parser is configured properly? That was the problem in my case. Use express's own body parser instead of bodyParser() constructor if that's what you are doing.

https://stackoverflow.com/questions/47232187/express-json-vs-bodyparser-json

    const express = require('express');
    app.use(express.json());

Hope this helps. Can you be more elaborate with your problem? Maybe share some code as well?

**Comment by gnusiva** [comment]
I faced a similar issue. In my case, it was a wrong post body. 

![image](https://user-images.githubusercontent.com/131292/69065208-64e56d80-0a45-11ea-8448-fdc3136a0c7f.png)

I was using form-data which results in a bad request. When i switched to x-www-form-urlencoded it works fine.

**Comment by HyperLoo** [comment]
> 
> 
> passport.authenticate("local") fetches username and password from the view engine.Try naming them username and password in the login form.

I am using username and password as names but still getting 'Bad Request' !!

**Comment by vinc01100101** [comment]
> Most of the problem i get was because the lib never mention body-parser as a dependency.

this 4 year old reply just ended my 2 hrs of debugging lol. been debugging til i see this and used bodyparser and boom it works! thanks!

**Comment by CtrlAltGiri** [comment]
I figured it out. 
Instead of using passport.authenticate(),  use User.authenticate() @Jyosiva

**Comment by Headache20** [comment]
> passport expects that in the form the names of username and password are those like that username and password, you are using pass for password, change the name in the html attributes.

thank you for this advice.... with advice i have solved my problem..

**Comment by Dr-CyberX** [comment]
you have to named your login form input as username and password same as i write because passport authenticate look form the same data via your view engine. so if you named it as Userpassword Userusername or any other name then change it to username and password.

**Comment by mruiz42** [comment]
I find that the documentation for passport is generally lackluster and not thoroughly detailed, which leads to confusion for new comers (me). It would be more helpful if the documentation was written in a style similar to Sequelize, where all api methods are described in great detail. I know it's open source software and a lot is community maintained and I am asking a lot as an outsider, but this is just my opinion and would like to see this great piece of software be improved.

Anyways, the comments here helped me solve my issue.

**Comment by mruiz42** [comment]
> `app.post('/login', (req, res) => passport.authenticate('local', { successRedirect: '/', failureRedirect: '/login', })(req, res));`

Thats for login, not protected routes

**Comment by AndreiG7** [comment]
> passport expects that in the form the names of username and password are those like that username and password, you are using pass for password, change the name in the html attributes.

Thank you! changing the name of the email input from 'email' to 'username' solved my problem, the annoying part is that it's not the first time when I make this mistake

**Comment by adhamale2810** [comment]
People who have posted the answer as change the input name to username and password are saviours.

**Comment by Mintuka** [comment]
> The `passport-local` example helped me find my error: https://github.com/jaredhanson/passport/blob/master/test/strategies/session.test.js
> 
> I had to use `req.isAuthenticated()` to check if the user was auth. Not make a call to `passport.authenticate('local')`.

passport.authenticate('local') if you name email/username form fields => name="username" in the schema too.

**Comment by gavinbelson** [comment]
@jaredhanson would you mind making passport local log out the errors. It silently fails with a "bad request" and nothing in the logs to point out issues.
The issue is that even when trying to add logging in the strategy itself, it fails before getting there:
`passport.use(new LocalStrategy(
  function(username, password, cb) {
    console.log('in strategy b4 db');  //never got here`
It's very tough to troubleshoot because with logins you are never sure if it's a cross site rejection, setup issue, route issue etc. 
I think the community would very much appreciate logging errors

**Comment by meandrewandyou** [comment]
Let's summarise it guys. 
First, make sure if you're using any json parser in you express middleware. Body-parser looks depricated, so hust make sure you have this line in your code: `app.use(express.json())`.
Second, sometimes people get 400 from passport.authenticate because of credentials. So make sure your axios requests from frontend to backend has this `{withCredentials: true}` as a parameter.
And finally, make sure to use "username" and "password" spelled exactly like this in your userSchema, in your frontend input names, and in your strategy options.  I used passport-local-mongoose, and looks like there's no need to configure local strategy, cause it use "username" and "password" by default.
Try any of this, 99% you'll be able to authenticate user and finally move on. Later, you'll find a way to specify "username" and "password" to be different, but for now I'm sure, your primary mission is to unstack)

**Comment by anudeep652** [comment]
> you have to named your login form input as username and password same as i write because passport authenticate look form the same data via your view engine. so if you named it as Userpassword Userusername or any other name then change it to username and password.

Thank you! it works

**Comment by riteshsinghh-coder** [comment]
var path= require('path');
var express=require("express");
var request=require("request");
const https=require("https");
const session=require("express-session");
const passport=require("passport");
const passportLocal=require("passport-local");
const passportLocalMongoose=require("passport-local-mongoose");
var app=express();
const bodyParser=require("body-parser");
const mongoose=require("mongoose");
const { Http2ServerRequest } = require('http2');
const multer=require("multer");
const { func } = require('assert-plus');
const { userInfo } = require('os');
const { ecNormalize } = require('sshpk');
app.set('view engine', 'ejs');
app.use(bodyParser.urlencoded({extended: true}));
app.use(bodyParser.json());
app.use(express.json()) ;


// const { stringify } = require('querystring');
app.use(express.static("public"));
app.use(session({
    secret:"Our little secret.",
    resave:false,
    saveUninitialized:false
}));
app.use(passport.initialize());
app.use(passport.session());

mongoose.connect("mongodb://localhost:27017/newhomesDB" ,{
    useNewUrlParser:true,
    // useFindAndModify: false, 
    useNewUrlParser: true, 
    useUnifiedTopology: true 
},err=>{
    if(err) throw err;
    console.log('Connected to MongoDB!!!')
});

const registerSchema=new mongoose.Schema({
    firstname:String,
    lastname:String,
    mobileno:String,
    email:String,
    
    password:String,
  
    // Password:Password

});



const propertySchema=new mongoose.Schema({
    submitprice:String,
    submitarea:String,
    submitbedroom:String,
    submitbathroom:String,
    submitmessage:String,
    submitcity:String,
    landmark:String,
    submittransaction:String,
    submitpropertytype:String,
    // PropertyLocality:String,
    Image:{
        data:Buffer,
        contentType:String
    },
})
registerSchema.plugin(passportLocalMongoose);
const Property=mongoose.model("Property", propertySchema);
const Detail=new mongoose.model("Detail",registerSchema);
passport.use(Detail.createStrategy());
passport.serializeUser(function(user, done) {
    done(null, user);
  });
  
  passport.deserializeUser(function(user, done) {
    done(null, user);
  });



app.get ('/', function(req,res){
    res.render("index");
})
app.get('/my-profile.html',function(req,res){
    if(req.isAuthenticated()){
        res.sendFile(__dirname+"/my-profile.html");
    }else{
        res.redirect("/login");
    }
});
app.post('/',function(req,res){
    
})
app.get('/register',function(req,res){
    res.render("register");
})
app.get('/login',function(req,res){
    res.render("login");
})

app.post('/register',function(req,res){
    
    const newUser=new Detail({
        firstname:req.body.firstname,
        lastname:req.body.lastname,
        email:req.body.email,
        mobileno:req.body.mobile,
        password:req.body.password

    })
    if(req.body.password==req.body.repeatpassword){
        Detail.register({username:req.body.email},req.body.password,function(err,detail){
            if(err){
                console.log(err);
                res.redirect("/register");
            }
            else{
                console.log("done");
                passport.authenticate('local')(req,res, function(){
                   
                    res.sendFile(__dirname+"/my-profile.html")
                })
            }
        })    
     }
    

    // res.sendFile(__dirname+"/my-profile.html");
   

})


app.post('/login',function(req,res){
   const user=new Detail({
    username:req.body.loginemail,
    password:req.body.password
   })

req.login(user, function(err){
    if (err) {
      console.log(err);
    } else {
      passport.authenticate("local")(req, res, function(){
        res.redirect("/my-profile.html");
      });
    }
  });
});





app.get('/submit-property.html',function(req,res){
    res.sendFile(__dirname+"/submit-property.html");
});


app.post('/submit-property.html',function(req,res){
  
    const register=new Property({
        submitprice:req.body.submitprice,
        submitarea:req.body.submitarea,
        submitbedroom:req.body.submitbedroom,
        submitbathroom:req.body.submitbathroom,
        submitmessage:req.body.submitmessage,
        submitcity:req.body.submitcity,
        landmark:req.body.landmark,
        submittransaction:req.body.submittransaction,
        submitpropertytype:req.body.propertytype,
        
        Image:{
            data:req.body.files,
        }
    
    });
    register.save();
    

})


app.post('/my-profile.html',function(req,res){
    if(req.isAuthenticated()){
        res.render("/my-profile.html");
    }else{
        res.redirect("/login");
    }
});
app.get('/estate-details-right-sidebar.html',function(req,res){
    res.sendFile(__dirname+"/estate-details-right-sidebar.html");
})

app.listen (3000,function(){
    console.log("server started on port 3000");
})

**Comment by riteshsinghh-coder** [comment]
its showing bad request

**Comment by alexchandan** [comment]
> passport expects that in the form the names of username and password are those like that username and password, you are using pass for password, change the name in the html attributes.

Thank You so much man. You can't believe I was stucked for about 4 hours in this. I can't express my word to thank you.
