### ISSUE TITLE
What if I want two Passport instances

### ISSUE THREAD

**Issue by ivanseidel** [jaredhanson/passport#376]
Hello,

I have used Passport for a long time, but now I reached a (possible) limitation with it, that I think it's important.

I'm building my app with express, and dividing it into '/client/...' and '/api/...'.

- `client` should only be accessed by Authenticated Facebook users
- `api` should only be accessed by Authenticated Admin users

and both `client` and `api` are in separate tables in the DB, and should keep logged in independently.

My Idea was that Passport had something like `require('passport').create()` so that we could isolate Passport applications, but I didn't found anything related to it.

Any thoughts?

**Comment by jaredhanson** [comment]
```js
var passport = require('passport');

var auth1 = new passport.Authenticator();
var auth2 = new passport.Authenticator();
```
