### ISSUE TITLE
Flash messaging doesn't work with android

### ISSUE THREAD

**Issue by emcenrue** [jaredhanson/passport#382]
See here for detailed explanation:

http://stackoverflow.com/questions/30955849/passports-req-flash-message-empty-for-only-certain-requests-for-failureredire

I've used passport for webapps before, and they work perfectly fine, but when I switch over to android it's like nothing is maintained through the middleware.

**Comment by jaredhanson** [comment]
Writing HTML-based apps and native apps is different, particularly with respect to flash messages.  Any such questions are not issues with this project, however.  Closing.
