### ISSUE TITLE
Network Proxy Issue

### ISSUE THREAD

**Issue by KenavR** [jaredhanson/passport#386]
Hi,

I am sitting behind a network proxy and when I authenticate my users on a third party website passport runs in a timeout. In this environment timeouts are almost always an issue with the proxy. Is there a way to configure passport to use a proxy?

thanks

**Comment by jaredhanson** [comment]
Passport itself does not make network requests.  Please identify the specific strategy and/or protocol you are using and file in issue on the corresponding project.
