### ISSUE TITLE
semver

### ISSUE THREAD

**Issue by iofjuupasli** [jaredhanson/passport#387]
> How do I know when to release 1.0.0?

> If your software is being used in production, it should probably already be 1.0.0. If you have a stable API on which users have come to depend, you should be 1.0.0. If you're worrying a lot about backwards compatibility, you should probably already be 1.0.0.

 - [x] used in production
 - [x] stable API
 - [x] backwards compatibility (there is no breaking changes every commit)

It's time for v1

**Comment by jaredhanson** [comment]
When I'm ready.
