### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by zwhitchcox** [jaredhanson/passport#393]
This isn't a huge deal, but the documentation is outdated. It still says to use ```express.session()``` and ```express.bodyParser()``` and ```express.cookieParser```. 

[This is in the "Configure" section under "Middleware"](http://passportjs.org/docs/configure)

**Comment by Kinnardian** [comment]
I think it's more than big enough and it will only get bigger. I also think this issue belongs here: https://github.com/passport/www.passportjs.org/issues/33

**Comment by zwhitchcox** [comment]
Oh ok, thanks!
