### ISSUE TITLE
Why did you make GET/logout? 

### ISSUE THREAD

**Issue by kulakowka** [jaredhanson/passport#394]
Explain me why did you make logout using `GET /logout` ?

It's not safe. Anyone malefactor can insert a picture  ```<img src="http://yousite.com/logout" />``` and your users will logged out. 

It may be better to do `POST /logout` ?

**Comment by doowb** [comment]
I think that's just in an example. You can use whichever method and route you like and just call `req.logout` inside it.

I think a common pattern is something like `POST /session` to create a new session when a user logins in, then `DELETE /session/:id` to log them out.

But you can also do `POST /login` to login and `POST /logout` to logout.

**Comment by Kinnardian** [comment]
A lot of examples are written this way. I think this is bad because it could probably be misconstrued to indicate a best practice or the only practice.

**Comment by jaredhanson** [comment]
File this issue against any examples that use `GET`.  Closing because this isn't actionable for this project specifically.

**Comment by Kinnardian** [comment]
OP should post here: https://github.com/passport/www.passportjs.org
