### ISSUE TITLE
multi strategy examples missing

### ISSUE THREAD

**Issue by embrown30** [jaredhanson/passport#396]
What happened to the multiple strategy examples linked here
https://github.com/jaredhanson/passport-local/tree/master/examples
Trying to implement authenticating using multiple strategies instead of one at a time.

**Comment by jaredhanson** [comment]
https://github.com/passport/express-3.x-http-basic-and-digest-example

https://github.com/jaredhanson/passport-local/tree/33d420ba5f54939c85adc5e4b61009db6467a900/examples
