### ISSUE TITLE
Session mixed up

### ISSUE THREAD

**Issue by mauris** [jaredhanson/passport#405]
Full question: http://stackoverflow.com/questions/32307933/passport-session-mixed-up

On our ExpressJS application, when pushed to production server, the passport session gets mixed up at random times. At random, the page can load the view of another user even when I did not log out of my session. Without doing anything else, another refresh will bring me back to my own account (at random too).

This phenomenon is happening to two of our web applications coded by two separate users following the Passport guides on their website. Both web apps use Facebook connect/API.

We followed the passportjs guide. Are we doing something wrong?

**Comment by mauris** [comment]
Suspected fix: `view cache` gets enabled on production mode and doesn't observe session / user pages. 

Setting `app.disable('view cache');` seems to fix the issue

**Comment by Kinnardian** [comment]
Hmmm, this seems urgent.

**Comment by jaredhanson** [comment]
This is not related to passport at all then

**Comment by mauris** [comment]
Yep Passport is working well. Initial suspect was Passport/Session because our stacks were all the same. thanks @jaredhanson and @Kinnardian
