### ISSUE TITLE
Integration with Hapi ?

### ISSUE THREAD

**Issue by sgentile** [jaredhanson/passport#406]
Is there any documentation from passport on using with Hapi ?

I'd like to use 4 different passport strategies in my application

Thanks!

**Comment by nelsonic** [comment]
@sgentile you're looking for: https://github.com/hapijs/bell 
relates to: https://github.com/dwyl/hapi-auth-jwt2/issues/100

**Comment by sgentile** [comment]
thank you - it was recommended to me to use bell as suggested - thanks for the help and feedback
