### ISSUE TITLE
PassportJS login fails (Local Strategy) silently

### ISSUE THREAD

**Issue by ianseyer** [jaredhanson/passport#407]
Hi all.

Fairly vanilla implementation here, however on login I get a *successful* failureRedirect trigger, despite none of my console log messages occurring in my strategy. This leads me to believe that PassportJS is eating an exception somewhere.

Stack:
Node v.12
Sequelize ORM on top of PostGres

Passport initialization :
```
var passport = require('passport')
  , LocalStrategy = require('passport-local').Strategy;

passport.use(new LocalStrategy(
  function(username, password, done) {
    console.log("USING PASSPORTJS");
    db.Admin.findOne({ username: username })
    .then(function(admin){
      if (!admin.validPassword(password)) {
        console.log('Invalid password');
        return done(null, false, { message: 'Incorrect password.' });
      }
      else if (admin === null) {
        console.log('Admin not found');
        return done(null, false, { message: 'Incorrect username.' });
      }
      return done(null, admin);
    })
    .catch(function(err){return done(err)});
  }
));

app.use(session({secret: "DEMANDFOOD"}))
app.use(passport.initialize());
app.use(passport.session());

app.post('/login',
  passport.authenticate('local', { successRedirect: '/menus',
                                   failureRedirect: '/login',
                                   failureFlash: false })
);

app.get('/login', function(req, res){
  res.render('auth/login.jade', {
    //...
  })
});
```

If it is relevant, I have defined my own validPassword method on my Admin model:
```
validPassword: function(password, done) {
        bcrypt.compare(password, this.password, function(err, res) {
            console.log(password);
            console.log(this.password);
            return res;
        });
      }
```

**Comment by jaredhanson** [comment]
What debugging have you done to isolate this as a passport issue?

**Comment by ianseyer** [comment]
Not to sound snarky, but it's the logging in component that doesn't work...?

Also, my failureRedirect works, which implies that passport is being called at some point along the line, but the unconditional console log from my strategy is not rendering.

**Comment by jaredhanson** [comment]
Not to sound snarky, but this is a widely used project, and what you describe is its only purpose, and it is known to be working.

More than likely this is some issue in your application, and filing an issue here causes me to spend time on things that I don't have time to spend on.  It helps maintainers of projects if you can do a bit of debugging prior to filing an issue, which saves both you and them (me, in this case) valuable time.

**Comment by jaredhanson** [comment]
Is your bcrypt logs getting printed?  Is the result what you expect?  This sort of information goes a long way...

**Comment by ianseyer** [comment]
No, it is not. 

I don't know how to debug, because my config is *exactly* the same as it appears on your website (except in places where I have explicitly stated they differ, such as using Sequelize ORM and a custom validPassword method). The only way I can think to debug is to `console log` things, which is not occurring.

The entirety of my application is functioning except for the login process.

**Comment by jaredhanson** [comment]
I'd bet your login request doesn't carry credentials correctly.  I'm not being sarcastic.  I don't believe its too much for me to ask you to help debug your issue.

**Comment by jaredhanson** [comment]
Do you have the bodyParser middleware so the credentials are parsed?

**Comment by ianseyer** [comment]
Fair - pardon me; text is an ambiguous medium. 

You were correct! My `bodyParsing` middleware was not implemented before my login handler. I was not aware of this because login is the only route I have in `app.js`; the rest of my routes (which also handle form input) are in seperate controllers.

Thank you for your time.

**Comment by tbjers** [comment]
Jesus wept.
