### ISSUE TITLE
Get user details of request from req.headers or req.query

### ISSUE THREAD

**Issue by kimmobrunfeldt** [jaredhanson/passport#410]
*I'm not sure if this issue belongs to passport or passport strategies, but posted it here to get started. I created the same issue to [passport-local repository](https://github.com/jaredhanson/passport-local/issues/116) too, feel free to close this if it belongs to the other repo.*

My API authentication currently works so that users send x-token header to authenticate: `x-token: <token>`. The details of my authentication request don't matter. I might want to send the token or user credentials in query parameters, headers or body.

It seems that passport strategies enforce that the credentials are pulled from `req.body` object. It would be more generic if I could pass a getter function which would get the credentials req object, like this:

```js
function(req) {
    return {apiKey: req.headers['x-token']};
}
```

What would be the best solution to overcome this? Create my own strategy? This problem exists at least in passport-local and passport-localapikey. Would you be willing to merge a pull request which would make the passport library API more generic?

I didn't find this problem mentioned in other issues.

**Comment by jaredhanson** [comment]
Yes, you need to create your own strategy.  Strategies can pull credentials from anywhere in the request, and are not limited to `req.body`.  The Bearer strategy pulls credentials from headers, as can be seen here: https://github.com/jaredhanson/passport-http-bearer/blob/master/lib/strategy.js#L89

It looks like this strategy already implements what you need: https://github.com/mbell8903/passport-auth-token
