### ISSUE TITLE
Where is the strategy naming scheme documented?

### ISSUE THREAD

**Issue by oliversalzburg** [jaredhanson/passport#412]
This has always confused me about passport. When I register a `BearerStrategy`, I can later use it to authenticate a route by using `passport.authenticate("bearer")`. From where should I infer that I have to use the string `bearer` here?

From what I can tell, it's simply a constant that is used in the strategy's constructor and I can only guess it, based on the name of the strategy, or by looking at the source of it.

Additionally, what if I need to use multiple `BearerStrategy` instances in my application? Can I assign different names to them? If so, how?

Is this documented somewhere and I'm simply missing it?

**Comment by oliversalzburg** [comment]
Possibly a duplicate of https://github.com/jaredhanson/passport/issues/50

**Comment by jaredhanson** [comment]
passport.use('foo', new BearerStrategy())

passport.use('bar', new BearerStrategy())

passport.authenticate('foo')

**Comment by Kinnardian** [comment]
I actually think this is a pretty important/useful feature. It took me days of pain to figure out. It's only mention closed to the bottom of the documentation. My team was looking at me like :/

**Comment by Kinnardian** [comment]
Additionally I believe this issue belongs here: https://github.com/passport/www.passportjs.org

**Comment by oliversalzburg** [comment]
Thanks for the help :)

This is really one of the aspects that was hardest for me to understand when reading the code samples. The string parameter that is used with `passport.authenticate()` seems to come out of nowhere. It is not made clear why this specific string needs to be used there.

IMHO, the documentation and examples would be much easier to understand if a name was always given when registering a strategy. That way the user will not be confused as to why a specific string is used. The option to not supply the name (and, thus, use the default name supplied by the strategy) should be noted, but I personally don't see the advantage.

Another option might be to expose the strategy name on the strategy itself, so you could use `passport.authenticate(BearerStrategy.name)`. Which I would also consider easier to grasp.

Thanks again for the support. Cheers

**Comment by KerimG** [comment]
Was this ever fixed or documented properly? Just stumbled across the same issue. Was bewildered, where the "jwt" string for JSONWebToken strategy came from.

**Comment by hrishioa** [comment]
Same issue, seven months later. Was this fixed?

**Comment by oliversalzburg** [comment]
No, this isn't documented anywhere and this hasn't changed in the past 5 years. I was also not requested to make documentation changes. If you want to use a strategy, just look at the source code.

**Comment by dhiegomaga** [comment]
It seems that one alternative is to specify your own strategy name, then you don't need to know the default strategy name. Eg: 

```ts
// local.strategy.ts

import { Injectable, UnauthorizedException } from '@nestjs/common'
import { PassportStrategy } from '@nestjs/passport'
import { Strategy } from 'passport-local'

@Injectable()
export class LocalStrategy extends PassportStrategy(Strategy, 'my-local-strategy') {
  constructor(private authService: AuthService) {
    super() // config Passport
  }

  async validate(username: string, password: string): Promise<any> {
    // const user = validateUser(...) -> your validation strategy
    // return user
    reuturn null
  }
}
```

```ts
// app.controller.ts

import { Controller, Get, Post } from '@nestjs/common'
import { Request } from '@nestjs/common'
import { UseGuards } from '@nestjs/common'
import { AuthGuard } from '@nestjs/passport'

@Controller()
export class AppController {
  constructor(private readonly appService: AppService) {}

  @UseGuards(AuthGuard('my-local-strategy'))
  @Post('login')
  login(@Request() req): any {
    return req.user
  }
}
```
