### ISSUE TITLE
uncaughtException: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by kauegimenes** [jaredhanson/passport#444]
passport v0.3.2
Node.js v0.10.37

I am getting a Maximum call stack size exceeded exception everytime i use the function `req.login`

````
uncaughtException: Maximum call stack size exceeded
{  
  "process": {
    "execPath": "/usr/local/bin/node",
    "version": "v0.10.37",
    "argv": [
      "/usr/local/bin/node",
      "/usr/lib/node_modules/pm2/lib/ProcessContainer.js"
    ],
    "memoryUsage": {
      "rss": 129265664,
      "heapTotal": 114848000,
      "heapUsed": 88313120
    }
  },
  "os": {
    "loadavg": [
      0.14013671875,
      0.12353515625,
      0.091796875
    ],
    "uptime": 3951782.155162147
  },
  "trace": [],
  "stack": null
}

`````

There is no stacktrace, but i was able to reproduce and the problem is related with `req.login`

https://github.com/jaredhanson/passport/blob/master/lib/http/request.js#L31

**Comment by jaredhanson** [comment]
Can you please provide details of the reproduction case.  There's nothing here to suggest that req.login is the culprit.

**Comment by jaredhanson** [comment]
Closing.  Reopen if details can be provided that point to an issue with Passport specifically.

**Comment by lifasky** [comment]
I m getting the same Maximum call stack size exceeded issue too. Can not find out why yet.

**Comment by kauegimenes** [comment]
@lifasky Your problem is releated with the req.login also? In my project the Maximum call stack size exceeded issue only happend when i call req.login

**Comment by lifasky** [comment]
Thanks for reply. It is some other issue. It solved.

On Tue, Jan 26, 2016 at 11:27 PM, Kauê Gimenes <notifications@github.com>
wrote:

> @lifasky <https://github.com/lifasky> Your problem is releated with the
> req.login also? In my project the Maximum call stack size exceeded issue
> only happend when i call req.login
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jaredhanson/passport/issues/444#issuecomment-175077628>
> .
>



-- 
Best,
Gloria
