### ISSUE TITLE
poorest documentation ever

### ISSUE THREAD

**Issue by pulkitnandan** [jaredhanson/passport#448]
Already took me a day to setup a simple session based authentication of frontend client and the rest api's and there's no tutorial or something that explains me these things. I mean is passport js provides just checking username password and no session like concept which can be easily implemented in some 10 lines of nodejs code by just checking username password in a middleware attached to every request. Is it a overkill for an app that requires just the session and the checking for username password from a vertica db. But its been very bad since I read this stackoverflow post some google's vp suggested this post to use it with angular js which is pretty to do in 48 hours. So is this post a scam or this usage of passport js is an overkill. Very fundamental question as relying on a library and getting stuck there doesn't seems reasonable when a similar thing can be achieved by just using genetice nodejs express js way.

**Comment by jaredhanson** [comment]
Thanks for the feedback.
