### ISSUE TITLE
why is req.user.id a thing

### ISSUE THREAD

**Issue by Jks15063** [jaredhanson/passport#449]
When I log req.user, I see an object such as:
`{ _id: '5678a71c4ad9189351235aeb', username: 'Jake', __v: 0 }`

When I log req.user.id (not _id), it logs the _id. 

Why does this happen and how do I turn it off, its not needed or wanted.

**Comment by jaredhanson** [comment]
This is not related to passport. It's probably MongoDB or some ORM you are using

**Comment by Jks15063** [comment]
Indeed, its mongoose.  I wasn't seeing the behavior anywhere else due to using lean().
