### ISSUE TITLE
Considering version 1.0

### ISSUE THREAD

**Issue by Yvem** [jaredhanson/passport#456]
passport is established. How about bumping to 1.0.0 ?

**Comment by capote** [comment]
it's got quite a bunch of issues and the owner doesn't seem too interested.  am I missing something?

**Comment by jaredhanson** [comment]
Most of the issues are not issues.

I've got a couple other minor cleanups to do before I consider things 1.0.0.  None of the API will change from 0.x to 1.0, so you can consider things stable.

**Comment by capote** [comment]
my apologies for doubting.

**Comment by Offirmo** [comment]
waiting for 1.0.0 to celebrate !
