### ISSUE TITLE
Update passport session after user info update

### ISSUE THREAD

**Issue by RonCan** [jaredhanson/passport#463]
I'm trying to update the passport session after user info change using:

    user.save(function(err) {
    if (err) return next(err)
    // What's happening in passport's session? Check a specific field...
    console.log("Before relogin: "+req.session.passport.user.changedField)

    req.login(user, function(err) {
        if (err) return next(err)

        console.log("After relogin: "+req.session.passport.user.changedField)
        res.send(200)
    })
    })

But even after re-login, with no errors my passport session remains the same. I have to manually logout and log back in for the session info to update. Can anyone explain what's happening?

**Comment by guilhermecl** [comment]
Did you manage to solve this?
thanks.

**Comment by eventengine** [comment]
Hey, dudes - whatta f*ck with Passport? We have are same trouble at the "battle project" in production.

**Comment by eventengine** [comment]
Try this:

`req.logout();
		req.login(updatedUser, function(err) {
			if (err) return next(err);
			
			res.render("edit", {
				isProfileUpdated: true,
				user: req.user
			});`

**Comment by RonCan** [comment]
This was a problem on my end. A collaborator was manually assigning the session somewhere and we solved it a long time ago. Closing
