### ISSUE TITLE
Library still mantained?

### ISSUE THREAD

**Issue by DiegoGallegos4** [jaredhanson/passport#467]
I want to use this for my app but i looked into the documentation and is outdated, specifically on the **configure middleware** part. Is still being mantained? Does it work on Express 4?

**Comment by TrejGun** [comment]
it works

**Comment by SCKelemen** [comment]
Doesn't look like it

**Comment by jaredhanson** [comment]
What basis do you make that assumption? Have you tried it? Does it work?  Do you want commits for the sake of commits?

**Comment by tbjers** [comment]
Jared, you are my spirit animal.

**Comment by joerx** [comment]
Mmh. 146 open issues and no commit in a year or so. It's a valid question I'd say.

**Comment by jaredhanson** [comment]
How many of the issues are people asking for support, rather than reporting an actual issue with the library?  Open source provides you a license for free code, not free support.

**Comment by joerx** [comment]
The question wasn't about support, it was about being maintained.

**Comment by SCKelemen** [comment]
I stand with joerx.

**Comment by jaredhanson** [comment]
If you have actionable issues that need fixing in the code base for this project, please report them or, if already reported, comment on an existing issue.

**Comment by jaredhanson** [comment]
And please read [How to Use Open Source and Shut the Fuck Up At the Same Time](http://hueniverse.com/2016/01/26/how-to-use-open-source-and-shut-the-fuck-up-at-the-same-time/)

**Comment by DiegoGallegos4** [comment]
@jaredhanson I see the question may have been misunderstood. The question was due because on reading the documentation I was using express 4 and some of the docs where from Express 3. Thanks for the clarification. How can we help you with updating the docs?

**Comment by jaredhanson** [comment]
@DiegoGallegos4 I didn't misunderstand the question.  If you find that the documentation is out of date, the title for an issue should not be "Library still mantained?"  Something like, "Documentation refers to out-of-date Express 3.x" or something would be more descriptive and helpful.

The docs are mostly here: https://github.com/passport/www.passportjs.org

Feel free to submit updates.
