### ISSUE TITLE
Possibility to remove (unused) strategies ? 

### ISSUE THREAD

**Issue by jaumard** [jaredhanson/passport#470]
Is there any way to remove a strategy after add it to passport ? 

For example if we have a website with a back office to enable/disable strategies it would be nice to just remove the strategy from passport instead of restarting the server.
Didn't find this on the documentation

**Comment by jaredhanson** [comment]
`passport.unuse` - https://github.com/jaredhanson/passport/blob/master/lib/authenticator.js#L60-L82
