### ISSUE TITLE
Cross-Domain problem in Authentication using node.js and angular.js

### ISSUE THREAD

**Issue by satyamakgec** [jaredhanson/passport#511]
i have try multiple methods to resolve the problem of CORS but i am unable to solve it . Please solve the issue how i can solve this problem  ----
XMLHttpRequest cannot load https://www.facebook.com/dialog/oauth?response_type=code&redirect_uri=http%…%3A3000%2Fauth%2Ffacebook%2Fcallback&scope=email&client_id=168567676883662. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.

**Comment by jaredhanson** [comment]
For security reasons, OAuth servers cannot allow cross domain requests the the authorization endpoint. The error you receive indicates that Facebook is correctly preventing you from doing this.
