### ISSUE TITLE
Flash message not working

### ISSUE THREAD

**Issue by rafaelferreiraql** [jaredhanson/passport#515]
I'm trying to work with Flash messaging in Passport, but failureFlash is doing absolutely nothing to the session. I'm about to give up and work with connect-flash directly instead of pushing errors via failureFlash, but here's my hope that I'm doing something very wrong.

Even weirder is that yesterday, failureFlash was actually pushing to flash (although I was having mighty trouble fetching it back then). Today I started it up to try again and the "flash" property was completely empty, no matter what I tried. Also, authentication itself works, my troubles are with flashing.

Oh, and I'm using Express 4.

My code looks something like this:
```
// Middleware
//Just to assure you session, passport and flash are all being used
app.use(logger('dev'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, 'public')));
app.use(session({ secret: 'antedeguemon', resave: true, saveUninitialized: true }));
app.use(passport.initialize());
app.use(passport.session());
app.use(flash());

// Strategy
passport.use(new LocalStrategy({ passReqToCallback: true},
    function(username, password, done) {
        // Insert authentication logic here
        return done(null, false); // In case the above fails
    }
));

// Act of authentication
router.post('/login', passport.authenticate('local', {
    successRedirect: '/data',
    failureRedirect: '/login',
    failureFlash: 'no dice',
});
);

// The login page itself
router.get('/login', function(req, res, next) {
    var mess = req.flash('error')
    console.log(mess); // This returns an empty array!!!
    res.render('login', { title: 'Log in', flash: mess });
};);

// And then the flash message is displayed in the "login" view via the 'flash' variable, or so it should be...
```

**Comment by rafaelferreiraql** [comment]
So, it seems it's not a Passport issue, but a Node.js one (or maybe it's Nodemon's fault). It somehow fixed itself after reinitialization.

**Comment by vivektiwarimp7** [comment]
failureFlash: 'no dice', to failureFlash: 'true',

**Comment by nanachi1** [comment]
may I ask what do you mean by reinitialization?

**Comment by Potoff** [comment]
Is anyone find a solution ?

**Comment by EmersonMedina** [comment]
I think he means restarting the project
