### ISSUE TITLE
How to stop passport from intercepting /login route?

### ISSUE THREAD

**Issue by yinanfang** [jaredhanson/passport#532]
I recently setup passport so that it runs on my API route, "/api/v1.0/login". However, it occurs that passport is also adding a route "/login" to the root app. Now all other login requests is intercepted by passport and the workflow is broken. For example, parse-dashboard authenticates at "POST /dashboard/login HTTP/1.1" and this no longer works. Is there a configuration that I can prevent passport from modifying the base app and only authenticate when I explicitly say
`"passport.authenticate('local', ...)` ?

**Comment by hongsolo9** [comment]
I don't see passport intercepting /login on my instance.

**Comment by yinanfang** [comment]
It was a pretty old question and I found a workaround
