### ISSUE TITLE
Consider exporting AuthenticationError constructor?

### ISSUE THREAD

**Issue by bradparker** [jaredhanson/passport#548]
First, thanks, passport is sooo handy :).

I'm asking about this just as a convenience in generic error handling code. It can be nice to switch on the error constructor:

```js
// some-auth-module.js

const passport = require('passport')
const { AuthenticationError } = passport

// ...

module.exports = {
  authenticate: passport.authenticate('somestrategy', {
    failWithError: true
  }),

  handleAuthenticationError: (error, request, response, next) => {
    if (error.constructor === AuthenticationError) {
      return response.status(401).send({
        message: error.message
      })
    }

    return next(error)
  }
}
```

```js
// my-app.js

app.post('/protected', authenticate, routeHandler)

app.use(handleAuthenticationError)
app.use(handleSomeOtherError)
// ... etc
```

Right now I'm requiring it from `lib/errors` from within Passport, which feels a little like a private api I'm digging around in.

Happy to continue doing so, if that's ok? Just thought I'd mention it. Happy to submit a PR if deemed a good idea.

Thanks, again.

**Comment by Mc128k** [comment]
I considered using it to check if something was a passport error (instanceof) instead of another error type, it should be safer than checking for a property that could not exist.

**Comment by rmartins0** [comment]
@bradparker was this implemented?

**Comment by bradparker** [comment]
@rmartins0 I'm sorry but I don't know. I closed the issue back in 2021 as I hadn't used passport for many years and was doing a clean up.

**Comment by rmartins0** [comment]
@bradparker for future reference to those who might need to do the same, I did it like this:

```
import AuthenticationError from 'passport/lib/errors/authenticationerror';
```
