### ISSUE TITLE
deserializeUser not being called

### ISSUE THREAD

**Issue by pvencill** [jaredhanson/passport#56]
Not sure what I"m doing wrong, if anything.  I have configured a LocalStrategy, and login seems to work fine, serializeUser gets called and works fine, but my req.user remains blank. req.session.passport is an empty object on subsequent requests, and putting a console.log statement in my deserializeUser logic shows that it's never called.

Here's the relevant code:

function authCallback(message, done){
  return function(err, user){   // gets called and has a user and no errors
        if(err){ console.error(err); return done(err);}
        else if(!user) { return done(null, false, {message : message}); }
        else {
          return done(null, user);
        } 
     }
}

passport.serializeUser(function(user,done){
    console.log('serializing user' + user.id); // logs a user id successfully
    done(null,user.id);
  })

  passport.deserializeUser(function(id, done){
    console.log('deserializeUser: ' + id); // never gets called
    User.findOne({_id : id}, done);
  });

  passport.use(new LocalStrategy(
    function(username, password, done) {
      User.authenticate(username, password, authCallback('Invalid username or password', done));  
    }  
  ));

  app.use(express.cookieParser(app.config.cookie_secret));  
  app.use(session_middleware);                                        // req.session setup before passport
  app.use(express.bodyParser());  
  app.use(express.methodOverride());                           

  // auth stuff
  app.use(passport.initialize());
  app.use(passport.session());

  app.use(app.router);

**Comment by ORESoftware** [comment]
where was your secure:true call?

**Comment by ORESoftware** [comment]
I am having same issue

**Comment by adrien-be** [comment]
Most probably in configuring the **express-session** module, as seen in the doc: https://github.com/expressjs/session

**Comment by SorcererSupreme** [comment]
i ran into the same problem. I guess the route for which deserializeUser() is not called, would be using a middleware or express-router (basically you have app.use() instead of app.get() or app.post()).

The route would be something like=> app.use('/book',isAuthorized,booksRouter).
where isAuthorized is a middleware and booksRouter is the router.

Now the deserialiseUser function is only called on app.get() or app.post() directly.

If you want to use app.use(), add passport.initialize() middleware like this: 
 app.use('/book',passport.initialize(), isAuthorized, booksRouter)

Hope it clears your doubt!

**Comment by rugglcon** [comment]
well hot damn, thank you @SorcererSupreme. I was putting my JWT middleware in my router.get and router.post, not app.use. thank you!

**Comment by nik72619c** [comment]
If anyone else is still facing the same issue, please check your fetch call, you probably have forgotten to include credentials
Worked for me

**Comment by Nases** [comment]
@SorcererSupreme I had,

  server.all('*', (req, res) => {
    return handle(req, res)
  })

at the end of my server config from Next.js custom server. 
Putting session only inside api route fixed the problem!

  server.use('/api',
    session({
      secret: 'secret',
      resave: true,
      saveUninitialized: true,
      cookie: {
        secure: process.env.NODE_ENV === 'production'
      }
    }), passport.initialize(),
    passport.session(),
    require('./assets/routes/index')
  )

This literally took 3 - 4 days to find a fix.

Thank you so much!
