### ISSUE TITLE
Call passport.authenticate outside of route

### ISSUE THREAD

**Issue by ROODAY** [jaredhanson/passport#577]
I'm trying to authenticate a user with username/password with data sent over socket.io. Since that's not a route, is there a way for me to call `passport-authenticate` and explicitly define the username/password I want to authenticate?

**Comment by James-Quigley** [comment]
The authenticate function is a middleware that takes in the request object, and performs the authentication based on how you created it within your strategy definition. If you're using the Local Strategy, you would have to attach the username/password to the request body, and pass that request to the authentication function.  I suppose in theory it could work, but I can't help but think you'd be better off just creating an endpoint for the authentication
