### ISSUE TITLE
req.isAuthenticated() returns false with a logged in user

### ISSUE THREAD

**Issue by srpalomino** [jaredhanson/passport#591]
I am testing for passport to recognize that a user is logged in, but even after they do login, req.isAuthenticated returns false. Does anyone know why this is happening?

`   
    

    const request = require('supertest')
    const express = require('express')
    const bodyParser = require('body-parser')
    const app = express()
    const passport = require('passport')
    const LocalStrategy = require('passport-local').Strategy
    const expressSession = require('express-session')

    const mongoose = require('mongoose')
    const url = "mongodb://user1:password1@ds155091.mlab.com:55091/redditmock"  
    mongoose.connect(url)

    //Configuring local authentication
    passport.use(new LocalStrategy(
        (username, password, done) => {
            User.findOne({username: username}, (err, user) => {
                if (err) return done(err)
                if (!user) {
                    return done(null, false, {message: 'Incorrect username.'});
                }
                if (user.password !== password) {
                    return done(null, false, { message: 'Incorrect password.' })
                }
                return done(null, user)
            })
        }
    ))

    //Configuring app to have sessions 
    passport.serializeUser((user, done) => {
        done(null, user._id)
    })
    passport.deserializeUser((id, done) => {
        User.findById(id, function(err, user) {
        done(err, user)
      })
    })

    app.post('/login', passport.authenticate('local'))

    app.post('/api/insertComment', (req, res) => {
        console.log(req.isAuthenticated())
    })

    app.use(bodyParser())
    app.use(expressSession({secret: 'aSecretKey'}))
    app.use(passport.initialize())
    app.use(passport.session())

    const server = app.listen(3000)

    describe('Routes', () => {
        before(done => {   
            //Logging in the user
            request(server)
                .post('/api/login')
                .type('form')
                .send({username: 'srpalo'})
                .send({password: 'secretpassword'})
                .then((res) => {
                    cookie = res.header['set-cookie'][0]
                    done()
                })
        })     
        it('/api/insertComment', (done) => {
            request(server)
                .post('/api/insertComment')
                .set('Content-Type', 'application/json')
                .set('Set-Cookie', cookie)
                .then((req, res) => {
                    done()
                })            
        })    
    })`

**Comment by smaclell** [comment]
I am pretty sure the issue is the order of the calls. You need to register your routes after adding the `session` middleware.

**Comment by benvium** [comment]
@srpalomino Did you ever find a solution? I'm have the same issue on occasion, though my routes are definitely registered after the session middleware is added.

**Comment by srpalomino** [comment]
@benvium I did find a solution: I assigned the cookie to the Cookie header

**Comment by AndrejGajdos** [comment]
@srpalomino Can you be more specific? What kind of cookie? I have the same issue.

**Comment by srpalomino** [comment]
@AndrejGajdos Ya no problem!

Check out these two sections:

1.  Get the cookie
https://github.com/srpalomino/reddit-clone/blob/master/tests/routes.js#L49-L60

2. Use the cookie
https://github.com/srpalomino/reddit-clone/blob/master/tests/routes.js#L77-L84

**Comment by AndrejGajdos** [comment]
@srpalomino Thanks for response. I found out I needed to add `withCredentials` flag in Axios, but it took me some time.
