### ISSUE TITLE
"Error: failed to deserialize user out of session" unwanted on production

### ISSUE THREAD

**Issue by hunterloftis** [jaredhanson/passport#6]
This is subjective but I believe a deserialization error from a _bad session cookie/reset redis database/other regular production hiccup_ should not totally stonewall the unfortunate user with the problem. As things stand now, as soon as you get a deserialization error you're essentially blacklisted, and the error will be useless information to a typical user.

More desirable production behavior includes any of:
1. Remove the session information and treat the user as a 'fresh' user who has not logged in
2. Allow for a configuration option that can override this behavior (eg, gracefulFailure: true)
3. Provide an override hook for handling failed deserializations, so the developer can at least override

**Comment by Luchooo** [comment]
This working for me, put the next following commands in your terminal:
`redis-cli`
`select 1`
`FLUSHALL`

**Comment by bengotow** [comment]
Just a heads up for folks stumbling across this—it turns out `TypeORM` returns `undefined` and not null. You should do something like `(await User.findOne({where: {id: obj.id}})) || false` for Passport to work properly.

**Comment by mifi** [comment]
created PR to fix undefined problem #975
