### ISSUE TITLE
New strategy for Slack

### ISSUE THREAD

**Issue by nmaves** [jaredhanson/passport#616]
The Slack Strategy that is on your site is no longer maintained.  I have created a new one where all of the current issues have been corrected.

https://github.com/nmaves/passport-slack-oauth2

If you would not mind updating your list of strategies and removing the old one that would awesome!

Per this update, you could close https://github.com/jaredhanson/passport/issues/566

**Comment by nmaves** [comment]
Any update on this?

**Comment by DragonRaider5** [comment]
How about submitting a PR?

**Comment by nmaves** [comment]
really @DragonRaider5 ?  For their front end website?

**Comment by DragonRaider5** [comment]
Oh that's my mistake - I'm sorry. I thought there was a list of strategies in the README, but this was the case for the available SessionStores in [express-session](https://github.com/expressjs/session) 📦

**Comment by jaredhanson** [comment]
`passport-slack-oauth2` is now searchable on [passportjs.org](http://www.passportjs.org).
