### ISSUE TITLE
drop the words "Simple" and "unobtrusive" from marketing copy

### ISSUE THREAD

**Issue by kevinburkeotto** [jaredhanson/passport#624]
I just spent about three hours determining why our tests were returning a 500 server error but the returned error contained no data and our 500 server error framework (the one that we've integrated into Express.js) was not logging anything.

It turns out Passport was rendering an HTML error page (including a stack trace(?) ) and returning immediately. This took a long time to debug because I had to determine on the client why the response was not JSON (and what the response actually was), and then on the server which piece of the response handling stack was executing and then returning without logging anything about what it was doing. Basically the only approach is to do a binary search and a) remove half of the middlewares until you don't see the error, then iteratively add them back until you find it or b) add print lines until you determine which print lines run and don't run, then iterate until you find the error.

In any event, my experience with 'Passport' was not that it was "simple" or "unobtrusive"; I would expect either of these things to let me know when it encountered an error condition instead of hiding it. It's bothersome that the library is being marketed this way.

**Comment by jaredhanson** [comment]
Perhaps you could point to the exact line inside passport where it is rendering an HTML error page with a stack trace?  I don't believe that passport is responsible for what you describe, but if it is it would be more productive use of an issue to get it fixed than complain about marketing copy. Thanks!
