### ISSUE TITLE
Monkey patching node http can conflict and is error prone

### ISSUE THREAD

**Issue by Pyrolistical** [jaredhanson/passport#628]
The moment you `require('passport')` the node http module is monkey patched. This is not cool.

This
https://github.com/jaredhanson/passport/blob/07bff37406241b0cf8db35986788d2dadbf93763/lib/index.js#L13
eventually calls
https://github.com/jaredhanson/passport/blob/07bff37406241b0cf8db35986788d2dadbf93763/lib/framework/connect.js#L29

There is no attempt to ensure it is not clobbering an existing method.

Monkey patching is fine, if control on **when** it occurs is controlled by the user. This way the user understand the monkey patching is happening.

I almost introduced a bug when removing passport, but one of my tests caught this issue.

**Comment by jaredhanson** [comment]
This is something I am planning to remove, and simply extend the `req` object as it passes through middleware, in the same way Express does.

Can you provide details about any issues or bugs this is currently causing, so that a fix can be tested and verified?

**Comment by VenPot** [comment]
@jaredhanson  has this been removed ?

**Comment by Pyrolistical** [comment]
Here's the scenario which will cause production bugs:
http.IncomingMessage.prototype.login =
  http.IncomingMessage.prototype.logIn = IncomingMessageExt.logIn;
  http.IncomingMessage.prototype.logout =
  http.IncomingMessage.prototype.logOut = IncomingMessageExt.logOut;
  http.IncomingMessage.prototype.isAuthenticated = IncomingMessageExt.isAuthenticated;
  http.IncomingMessage.prototype.isUnauthenticated

**Comment by mattratliff** [comment]
I'm having this issue as well.  As soon as I require passport I get the error in my ionic app as follows:

TypeError: Cannot read property 'prototype' of undefined
    at Function.exports.__monkeypatchNode (http://localhost:8100/build/vendor.js:99498:24)

Line 99498 in vendor.js is as follows:

exports.__monkeypatchNode = function() {
  var http = __webpack_require__(252);
  var IncomingMessageExt = __webpack_require__(259);
  
  <red>http.IncomingMessage</red>.prototype.login =
  http.IncomingMessage.prototype.logIn = IncomingMessageExt.logIn;
  http.IncomingMessage.prototype.logout =
  http.IncomingMessage.prototype.logOut = IncomingMessageExt.logOut;
  http.IncomingMessage.prototype.isAuthenticated = IncomingMessageExt.isAuthenticated;
  http.IncomingMessage.prototype.isUnauthenticated = IncomingMessageExt.isUnauthenticated;
};

**Comment by wi-ski** [comment]
This is an extremely bad thing to trip over. Is there any chance this could get removed?

**Comment by jaredhanson** [comment]
Monkey patching has been removed in `passport@0.5.0` (by way of #848).

For more information, see the [announcement](https://medium.com/passportjs/passport-v0-5-0-cce2245e3d3c) on the blog and [details](https://github.com/jaredhanson/passport/blob/master/CHANGELOG.md#050---2021-09-23) in the CHANGELOG.
