### ISSUE TITLE
facebook failure url not working!

### ISSUE THREAD

**Issue by jamalabo1** [jaredhanson/passport#639]
code : 
**app.get('/auth/facebook/callback',
  passport.authenticate('facebook', { session:true, failureRedirect: '/login' }),
  function(req, res) {
    // Successful authentication, redirect home. 
    res.redirect('/dashboard');
  });**

Passportjs Not Redirecting after facebook error return 
( i set the vaild url is localhost:300 and i do : 
var server = http.createServer(app);
server.listen(80); 

and then making a log in it says that the URL is invalid! this is not the problem when return to /auth/facebook/callback its says 

Error
    at Strategy.authenticate (%Path%\node_modules\passport-facebook\lib\strategy.js:79:23)
  \lib\router\route.js:131:14)

**Comment by pronebird** [comment]
Please improve the formatting of your issue.
