### ISSUE TITLE
Add TLS to website

### ISSUE THREAD

**Issue by andrewbanchich** [jaredhanson/passport#657]
<img width="496" alt="tls" src="https://user-images.githubusercontent.com/13824577/36907858-ab66fdae-1e07-11e8-97ad-cfab55ab83e4.png">

Seems ironic. Could we add TLS to the website?

**Comment by mzk** [comment]
One-year-old issue and still isn't fixed? What's about https://letsencrypt.org/ or https://cultivatehq.com/posts/elixir-https-cowboy/ Or GitHub static pages over https?

**Comment by jakehemmerle** [comment]
Still not here in April 2020 :)

**Comment by volodymyrrudyi** [comment]
This is amazing. The absolute leader of NodeJS authentication implementation doesn't have TLS configured on their landing page.

How can we help to make this happen?

**Comment by jaredhanson** [comment]
The website is now available with TLS at https://www.passportjs.org.
