### ISSUE TITLE
Impossible to connect when using jwt

### ISSUE THREAD

**Issue by frozenfroggie** [jaredhanson/passport#671]
Hi,
I want to use jwt rather than session. But endpoint metioned in documentation:
```
app.get('/connect/twitter',
  passport.authorize('twitter-authz', { failureRedirect: '/account' })
);
```
can be reached only by redirection using `<a href='/connect/twitter'>`, XMLHttpRequest is not possible due to CORS error (it will automatically attempt to redirect the browser to the strategy's service). So I cant send token to server, user data encoded in token cant be reached, and so new social user data cant be merged and saved into database. In conslusion, social connections can be done only using session on server. Sorry if I misunderstood sth.

**Comment by jaredhanson** [comment]
Per instructions in the [issue template](https://github.com/jaredhanson/passport/blob/master/.github/ISSUE_TEMPLATE.md), please post questions on the [discussion forum](https://github.com/passport/discuss).

Closing.
