### ISSUE TITLE
http://www.passportjs.org/packages/ 404

### ISSUE THREAD

**Issue by scottp** [jaredhanson/passport#675]
The documentation page on the URL above is a 404. Click "Stratergies" anywhere on the site, and you get a 404 to the URL above

### Expected behavior
I think it used to list all the straterties (500) and searchable.

### Actual behavior
404

### Steps to reproduce
Go to URL

### Environment

NA. Any browser.

**Comment by morteryler** [comment]
The owner of the site scored on the project.
Use this: https://github.com/jaredhanson/passport/wiki/Strategies

**Comment by cjke** [comment]
Do you mean the owner of the site is different to the owner of passportjs? Or its the same, and they have abandoned both (the site and the project)?

**Comment by williamli** [comment]
@cjke i want to know too. or is the whole passport project abandoned? (I am new to passport.js)

**Comment by jaredhanson** [comment]
The project is not abandoned.  The strategy list depends on JavaScript, so if its not working it most likely means JavaScript is disabled in the browser.

In any case, whether or not the site is working has nothing to do with `passport` the package, which is stable and has been for a long time.  Thanks.

**Comment by cjke** [comment]
I can assure you JS wasn't disabled in the browser. However, it does look like the page is now working - maybe there was a release between now and the May when the issue was raised...
Eitherway, glad it is back up and running

**Comment by williamli** [comment]
@cjke it wasn't working an hour ago but it's working again now. spooky

http://www.passportjs.org/packages/

**Comment by cjke** [comment]
Interesting. If you navigate directly to it, it fails (completely). 
I'm guessing there is some frontend routing going on but nginx (or apache) isn't set up correctly?

cc @jaredhanson

**Comment by jaredhanson** [comment]
If someone wants to submit a patch, the code for the website is here: https://github.com/passport/www.passportjs.org

However, whether or not a page on the website is working correctly has nothing to do with the stability or maintenance of the package itself.

**Comment by cjke** [comment]
Thanks for the clarification. I'm not going to raise a PR, as I know nothing really about this project - I'm a complete newcomer to passport and was just trying to track information. 

I understand the site doesn't reflect the stability of the project, but as someone possibly coming into the passport community, it's not the most reassuring thing either.

Goodluck with your ongoing efforts with passport

**Comment by williamli** [comment]
yeah I agree with @cjke 
I am looking for an auth package for a GraphQL project and want to make sure I picked the _right_ one.

I did a search on **abandoned** here and there were 2 issues here that had me worried earlier and trigged my initial query about the sustainability of this platform
