### ISSUE TITLE
I want to add an IF condition before passport.authenticate, is it possible?

### ISSUE THREAD

**Issue by wirespecter** [jaredhanson/passport#681]
Instead of this:
```
app.post('/login', 
  passport.authenticate('local', { failureRedirect: '/login' }),
  function(req, res) {
    ...
  });
```

I want to do this:
```
app.post('/login', function (req, res) {
    if (req.body.A_RANDOM_BOOLEAN_VALUE) {
       passport.authenticate('local', {failureRedirect: '/login'});
    }
});
```

Is it possible or am I missing something?

I know that I can check for `req.body.A_RANDOM_BOOLEAN_VALUE` in the `local` LocalStrategy but I don't want to because it is going to mess with the application's design.

Thanks for reading this, if I said anything that doesn't make sense please let me know.

### Environment

* Operating System: Ubuntu 16.04.2 LTS
* Node version: v7.10.1
* passport version: passport@0.3.2

**Comment by jaredhanson** [comment]
Per instructions in the [issue template](https://github.com/jaredhanson/passport/blob/master/.github/ISSUE_TEMPLATE.md), please post questions on the [discussion forum](https://github.com/passport/discuss).

Closing.
