### ISSUE TITLE
How to pass a password to a user session if there is no req in the strategy?

### ISSUE THREAD

**Issue by morteryler** [jaredhanson/passport#682]
#### Are you looking for help?

Yes.
This is not an instagram problem, it's your library.

#### Is this a security issue?

No.

I can not safely transfer data to the callback success in order to be able to record a user session.

### Expected behavior
Something like this:
```
passport.use(new InstagramStrategy({
    clientID: INSTAGRAM_CLIENT_ID,
    clientSecret: INSTAGRAM_CLIENT_SECRET,
    callbackURL: 'http://'+my_ip+'/login/auth/instagram'
  },
  function(accessToken, refreshToken, profile, done, req) {
    process.nextTick(function() {
    req.session.password = "mypass"; // GOOD
});
    	return done(null, profile);
    });
  }
));
```

### Actual behavior
This code:
```
router.get('/auth/instagram',
	passport.authenticate('instagram', {
		failureRedirect: '/'
	}),
	function(req, res) {
		req.session.password = // How do I get data so that no errors occur?
		res.redirect('/profile');
	}
);
```
I need to transfer data safely to record the session.

### Steps to reproduce
```
let o = {};
passport.use(new InstagramStrategy({
    clientID: INSTAGRAM_CLIENT_ID,
    clientSecret: INSTAGRAM_CLIENT_SECRET,
    callbackURL: 'http://'+my_ip+'/login/auth/instagram'
  },
  function(accessToken, refreshToken, profile, done) {
    process.nextTick(function() {
         let pass = "password";
         o.pass = pass; //BAD CODE
return done(null, profile);
    });
  }
));
```

### Environment

* Operating System: Linux arch 4.16.9-1-ARCH #1 SMP PREEMPT Thu May 17 02:10:09 UTC 2018 x86_64 GNU/Linux
* Node version: v10.1.0
* passport version: 0.4.0

**Comment by jaredhanson** [comment]
Per instructions in the [issue template](https://github.com/jaredhanson/passport/blob/master/.github/ISSUE_TEMPLATE.md), please post questions on the [discussion forum](https://github.com/passport/discuss).

Closing.
