### ISSUE TITLE
Why did you stop supporting: passport-wargaming?

### ISSUE THREAD

**Issue by LesoR** [jaredhanson/passport#685]
And where to find documentation on the old passport-wargaming?
Please start again to support passport-warehanging! Very useful package

**Comment by jaredhanson** [comment]
passport-wargaming is (was?) a strategy implemented by another developer.  Please contact that developer for information.

**Comment by LesoR** [comment]
Here's what I found: http://prntscr.com/k3zmcm (Screenshot).
At transition, produces an error: http://www.passportjs.org/packages/passport-wargaming/
I could not find any contacts with the developer :(

And in the code that is, it's hard for a newcomer to understand:
[https://registry.npmjs.org/passport-wargaming/-/passport-wargaming-0.0.1.tgz](url)

Help, plz.
