### ISSUE TITLE
Can we migrate away from Make files?

### ISSUE THREAD

**Issue by DanielRuf** [jaredhanson/passport#694]
### Expected behavior

I should be able to build and use all commands as contributor, also on Windows.

### Actual behavior

Currently we need make to build passport but this can not be used on Windows and other OS.

### Environment

* Operating System: Windows 10
* Node version: 
* passport version:

**Comment by dvogel** [comment]
GNU make is available for windows. Here's a few distros:

https://chocolatey.org/packages/make
http://gnuwin32.sourceforge.net/packages/make.htm

**Comment by DanielRuf** [comment]
> I should be able to build and use all commands as contributor, also on Windows.

Without any further tools. This project was created with Node.js and does not need such a dependency. A small JS script could do this too.

**Comment by jaredhanson** [comment]
Which make targets are you wanting to run without make?  The `npm test` script doesn't require make.

**Comment by DanielRuf** [comment]
> and use all commands as contributor

The make file includes docs viewing, coverage report viewing and cleanup.

These things can be done with `rimraf`, `opn`/`open` and so on.
