### ISSUE TITLE
Google+ Sign-In Deprecation

### ISSUE THREAD

**Issue by ginovski** [jaredhanson/passport#713]
Hi there,

We are using passport.js to authenticate people with their Google account. And I'm receiving emails from Google last days that we are using something that's going to be fully deprecated. Screenshot of the email below: 

<img width="636" alt="screenshot 2019-01-30 at 10 40 44" src="https://user-images.githubusercontent.com/6017552/51969030-09c59880-247c-11e9-9569-9242beae8a47.png">

Here is the code we have for authentication:

`const options = {`
     `authType: "rerequest",`
            `state: JSON.stringify(data),`
            `session: false,`
            `failureRedirect: "/login",`
            `scope: ["profile", "email"],`
        `};`
`passport.authenticate("google", options)(req, res, next);`

Are you going to update the api you are making requests to? Or should I update something in my code?  

### Environment

* passport@0.3.2
* passport-google-oauth20@1.0.0

**Comment by devalexqt** [comment]
Same problem.

**Comment by tima101** [comment]
@ginovski You can use forked package for now: https://github.com/builderbook/builderbook/issues/195

**Comment by ginovski** [comment]
@tima101 Do you know what's going on with passport.js? I see that they haven't updated almost anything last months. If you can make a pull request with your updated version to the original repository.

**Comment by ginovski** [comment]
@jaredhanson Are you going to review this PR? 
https://github.com/jaredhanson/passport-google-oauth2/pull/51

**Comment by archiebaer** [comment]
You may find this useful: https://stackoverflow.com/a/54112673/10124491

**Comment by Yacine-A** [comment]
Any update on the PR ? would be nice to pull the trigger on it

**Comment by jaredhanson** [comment]
`passport-google-oauth20@2.0.0` has been published to npm.  More information here: https://medium.com/passportjs/google-api-shutdown-330c3b47e3df
