### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by claytongulick** [jaredhanson/passport#720]
This is a great project, and I've used it in many personal and professional projects.

It doesn't look like there have been meaningful updates to this project since 2017? There are 30 PRs sitting in queue.

I see there is a fork, over at https://github.com/passport-next/passport

I'm trying to determine if this project is still active, or if the fork should be used?

AFAIK this is the most popular authentication technique for express, it is a shame for it to get stale. Are you looking for a new maintainer?

Thanks!

**Comment by jaredhanson** [comment]
This project is still active.  If you want to follow updates as PRs and other changes are published, follow the blog on Medium: https://medium.com/passportjs
