### ISSUE TITLE
Planning2018

### ISSUE THREAD

**Issue by kombinations** [jaredhanson/passport#723]
** READ THIS FIRST! **

#### Are you looking for help?

Reminder: The issue tracker is not a support forum.

Issues should only be filed in this project once they are able to be reproduced
and confirmed as a flaw in the software or incorrect information in associated
documention.

If you are encountering problems integrating this module into your application,
please post a question on the [discussion forum](https://github.com/passport/discuss)
rather than filing an issue.

#### Is this a security issue?

Do not open issues that might have security implications.  Potential security
vulnerabilities should be reported privately to jaredhanson@gmail.com.  Once any
vulerabilities have been repaired, the details will be disclosed publicly in a
responsible manner.  This also allows time for coordinating with affected parties
in order to mitigate negative consequences.

If neither of the above two scenarios apply to your situation, you should open
an issue.  Delete this paragraph and the text above, and fill in the information
requested below.

### Steps to reproduce

```js
// Format code using Markdown code blocks
```

### Environment

* Operating System: 
* Node version: 
* passport version:

**Comment by jaredhanson** [comment]
There's no content in this issue, besides the template. Closing.
