### ISSUE TITLE
How to get the Authorization Code

### ISSUE THREAD

**Issue by pet2131** [jaredhanson/passport#737]
Hello,

I'm having a trouble getting the authorization code when authorize against oAuth2 API. I've looked into calback request but no luck.

Best Regards

**Comment by jaredhanson** [comment]
Please provide more details.  What OAuth provider are you using, and why do you need the authorization code?  The authorization code is typically a temporary, one-time code, which Passport uses internally.  The code is exchanged for an access token, which Passport does provide.

**Comment by pet2131** [comment]
> Please provide more details. What OAuth provider are you using, and why do you need the authorization code? The authorization code is typically a temporary, one-time code, which Passport uses internally. The code is exchanged for an access token, which Passport does provide.

Hello,
I'm using custom OAuth provider(not facebook, azure, etc,).
After the token expires I need to refresh it - for that purpose I need the Refresh Token and the Authorization Code. 
I believe that I found it - in 163 line in strategy.js

Is there more convenient way to get it?


Keep up the good work!
Best Regards

**Comment by pet2131** [comment]
> > Please provide more details. What OAuth provider are you using, and why do you need the authorization code? The authorization code is typically a temporary, one-time code, which Passport uses internally. The code is exchanged for an access token, which Passport does provide.
> 
> Hello, @jaredhanson
> I'm using custom OAuth provider(not facebook, azure, etc,).
> After the token expires I need to refresh it - for that purpose I need the Refresh Token and the Authorization Code.
> I believe that I found it - in 163 line in strategy.js
> 
> Is there more convenient way to get it?
> 
> Keep up the good work!
> Best Regards

Hello, @jaredhanson, are there any updates on this?
