### ISSUE TITLE
Authentication is delayed (fails) more often in a random fashion the more logic is inside deserializeUser

### ISSUE THREAD

**Issue by Twiggeh** [jaredhanson/passport#742]
After calling req.login(), req.isAuthenticated() fails sometimes.

### Expected behavior
Never fail

### Actual behavior
Fails sometimes, the faster you log out and back in the more likely it is to fail. With breakpoints it doesn't fail at all. 

### Steps to reproduce
Tested with the local strategy since it is the fastest to log in and out : 

1. Have two User-models and switch between them like in the example below.
If the lines with user.userType = ...; stay commented the failure rate is at about 5%, uncommenting them puts the failure rate above 80%; 

2. The successful login redirect (example below) needs a middleware (example below)  to check for authentication

3. Log in and out (probably will make a recording)

#### Serialize and deserialize functions
```js
 passport.serializeUser((user, done) => {
    let userType;
    let userPrototype = Object.getPrototypeOf(user);
    if (userPrototype === SCUser.prototype) {
      userType = 'SCUser';
    } else if (userPrototype === Customer.prototype) {
      userType = 'Customer';
    }
    const userInfo = new UserInfo(user.id, userType, '');
    done(null, userInfo);
  });

  passport.deserializeUser((userInfo, done) => {
  //The more logic is inside this the more likely the authentication is to be very delayed
    if (userInfo.userType === 'SCUser') {
      SCUser.findById(userInfo.userId, (err, user) => {
        //user.userType = 'SCUser';
        return done(err, user);
      });
    }
    if (userInfo.userType === 'Customer') {
      Customer.findById(userInfo.userId, (err, user) => {
        //user.userType = 'Customer';
        return done(err, user);
      });
    }
```
#### Successful login redirect route
```js
    router.get('/dashboard/:type?/:id?', isAnyAuthenticated, (req, res) => {
    ....
    }
```
#### isAnyAuthenticated Middleware
```js
const isAnyAuthenticated = (req, res, next) => {
  if (req.isAuthenticated()) next();
  else {
    //prettier-ignore
    return res.redirect('/auth/login' +setAllMessages([{errors: ['To access this you need to be logged in. isAnyAuthenticated']}]));
  }
};
```

### Environment

* Operating System: Windows 10 
* Node version:  v10.15.3
* passport version: `-- passport@0.4.0

**Comment by jaredhanson** [comment]
Could you provide details as to why the issue was closed?

**Comment by Twiggeh** [comment]
Oh sorry I didn't post the solution my bad :) 

Replacing res.redirect with the code below seems to fix this issue
```js
req.session.save(function(){
  res.redirect
});
```
credit : https://github.com/jaredhanson/passport/issues/306#issuecomment-103413761
