### ISSUE TITLE
Passportjs.org is down/malfunctioning

### ISSUE THREAD

**Issue by codingedward** [jaredhanson/passport#751]
Hello, thanks for this wonderful library!

For the past few days, `passportjs.org` has been down (in that it does not render correctly). I have also tried using different browsers.

Here's a screenshot of how it appears:
![Screenshot 2020-01-04 at 19 22 29](https://user-images.githubusercontent.com/15171489/71768604-854f8580-2f28-11ea-8d24-60cae0f48aa4.png)

On inspecting, the following errors are visible:
```
GET http://www.passportjs.org/assets/styles/all.css net::ERR_ABORTED 504 (Gateway Timeout)

GET http://www.passportjs.org/script/main.js net::ERR_ABORTED 504 (Gateway Timeout)
```

**Comment by jaredhanson** [comment]
No issues on my end?  Can you confirm its not something local to your network?

**Comment by codingedward** [comment]
@jaredhanson, I just cleared the application cache and its working now. Thank you 🙇 .
