### ISSUE TITLE
Official website `http://www.passportjs.org/packages/` return `Not Found`

### ISSUE THREAD

**Issue by yeongjet** [jaredhanson/passport#765]
Where I can find strategies?

**Comment by quinncheong** [comment]
Hi @yeongjet , I think you can just go to the official website http://www.passportjs.org and you will find a search bar directly at the top. You can also access the strategies through the left column as there will be a tab with the word 'Strategies' on them. Once in, just start typing for the strategy which you want to use. Hope this helps.
