### ISSUE TITLE
SSL Cert expired/missing

### ISSUE THREAD

**Issue by Gibbo3771** [jaredhanson/passport#767]
The SSL certificate on the libraries website has expired or is missing.

### Expected behavior
Visiting [the website](https://www.passportjs.org/) should work without SSL errors.

### Actual behavior
Does not load as secure.

### Steps to reproduce
Visit the website

### Environment

* Firefox 74.0 (64-bit)
* Operating System: Manjaro Linux 
* Kernel Version: 5.4.27-1-MANJARO
* OS Type: 64-bit

**Comment by MalteMagnussen** [comment]
Thanks. Came here to make this issue. 
Quite funny that a security site doesn't have SSL certificate. 
Trying to implement OAuth 2.0 for the first time as a student, and saw this: 
![image](https://user-images.githubusercontent.com/11192971/82053440-a89bf580-96bd-11ea-92ee-b005b7578209.png)

**Comment by Gibbo3771** [comment]
@MalteMagnussen Yeah it's a very bad image haha. I still can't believe it isn't fixed. It's not like the community can fix it!

Who do we ping to bring this to the attention of the website maintainer?

**Comment by cd4d** [comment]
It's worrying that nobody bothered to update the certificate. Is this project still maintained?

**Comment by jaredhanson** [comment]
The website is now available with TLS at https://www.passportjs.org.
