### ISSUE TITLE
Issue with "Search for Strategies" button

### ISSUE THREAD

**Issue by dasjideepak** [jaredhanson/passport#774]
When I am clicking on search icon on "Search for Strategies" button

![Screenshot_20200514_121951](https://user-images.githubusercontent.com/38307844/81902337-9a76a800-95dd-11ea-9f76-a5e03c3444f5.png)

It is redirecting me to a "Not Found" page

![Screenshot_20200514_122053](https://user-images.githubusercontent.com/38307844/81902374-a7939700-95dd-11ea-8729-140e607856a5.png)

**Comment by dasjideepak** [comment]
I want to work on this issue, I can fix it.

**Comment by tbhaxor** [comment]
> I want to work on this issue, I can fix it.

This problem is with the website, you need to have the source code of the website
