### ISSUE TITLE
Improve documentation with complete examples

### ISSUE THREAD

**Issue by AdityaAnand1** [jaredhanson/passport#779]
Shouldn't all strategies include complete documentation instead of snippets?

For e.g: http://www.passportjs.org/packages/passport-local/

IMO All strategy docs should contain the following to provide maximum value and quick onboarding to all users:

1. E.g API endpoints: /signup /login /forgot-password
2. Examples for authenticating specific endpoints (blacklisting/whitelisting)
3. Example middleware
4. Complete error handling
5. Token/Session logic
6. Possible combinations of different strategies (e.g Bearer token + local strategy) or rather, recommended patterns.

I realize this would be a major overhaul, but would inevitably make this library far more valuable 😁

**Comment by jaredhanson** [comment]
Would you volunteer to write this documentation?

**Comment by AdityaAnand1** [comment]
I would, but I've only used passport once for a hobby project in 2014 and just started checking it out again, so probably not the best person.

**Comment by jaredhanson** [comment]
Ok.  I'm going to close this then, as its not a priority and not a functionality issue with this module.  The community has published ample tutorials and docs.  Always room for improvement, of course.  But without an owner, this isn't actionable.

**Comment by AdityaAnand1** [comment]
Wow.
