### ISSUE TITLE
Website SSL

### ISSUE THREAD

**Issue by jonabitz** [jaredhanson/passport#784]
You guys are all about auth and security. 
Not having an SSL on your website is a bad look and takes 5min to rectify.

Not here to throw stones - I'm equally guilty of not giving our website any love or attention and few min ago just rectified same ssl issue for us. For you I see it as more important...

**Comment by tripol** [comment]
And this is still not fixed?

**Comment by jaredhanson** [comment]
The website is now available with TLS at https://www.passportjs.org.
