### ISSUE TITLE
Broken example link in passport-local document

### ISSUE THREAD

**Issue by pjs21s** [jaredhanson/passport#806]
[passport-local](http://www.passportjs.org/packages/passport-local/)

I found `Examples` link is broken in that page.

[examples](https://github.com/jaredhanson/passport-local/tree/master/examples)

**Comment by am-jake** [comment]
I believe the link should now be 
https://github.com/jaredhanson/passport-local/wiki/Examples

**Comment by pjs21s** [comment]
Good thank you
