### ISSUE TITLE
Suggestion: Use Github's Discussions feature

### ISSUE THREAD

**Issue by itayganor** [jaredhanson/passport#807]
I have just discovered there's [a whole repository dedicated to discussions about Passport.js](https://github.com/passport/discuss).

Nowadays we have [Github Discussions](https://docs.github.com/en/discussions), a better solution for support threads, all in this main repository. I think Passport.js could benefit from turning on this feature, enabling it to have a dedicated community forum.

**Comment by jaredhanson** [comment]
Done.
