### ISSUE TITLE
Postgres example uses Mongodb

### ISSUE THREAD

**Issue by esimim** [jaredhanson/passport#841]
** READ THIS FIRST! **

#### Are you looking for help?

Reminder: The issue tracker is not a support forum.

Issues should only be filed in this project once they are able to be reproduced
and confirmed as a flaw in the software or incorrect information in associated
documention.

If you are encountering problems integrating this module into your application,
please post a question on the [discussion forum](https://github.com/passport/discuss)
rather than filing an issue.

#### Is this a security issue?

Do not open issues that might have security implications.  Potential security
vulnerabilities should be reported privately to jaredhanson@gmail.com.  Once any
vulerabilities have been repaired, the details will be disclosed publicly in a
responsible manner.  This also allows time for coordinating with affected parties
in order to mitigate negative consequences.

If neither of the above two scenarios apply to your situation, you should open
an issue.  Delete this paragraph and the text above, and fill in the information
requested below.

The provided example in the Documentation is actually using mongodb instead of Postgres on node.js, why is that?

### Expected behavior

I would expect the Postgres example to use Postgres database.

### Actual behavior

Mongodb is being used in the example.

### Steps to reproduce

Read the documentation. The Postgres example actually uses mongodb
```js
// Format code using Markdown code blocks
```

### Environment

* Operating System: 
* Node version: 
* passport version:

**Comment by jaredhanson** [comment]
I'm not sure what example this is referring to.
