### ISSUE TITLE
crash since the last version when authenticating

### ISSUE THREAD

**Issue by rafipiccolo** [jaredhanson/passport#854]
it used to work well, and the new version broke the website.
authentication now crashes server

passport-facebook 3.0.0
which uses passport-oauth2 1.5.0
passport 0.5.0
node v16.10.0

here is the stack trace :
```
uncaughtException req.logIn is not a function {
     "err": {
         "code": null,
         "name": "TypeError",
         "message": "req.logIn is not a function",
         "detail": null,
         "stack": [
             "TypeError: req.logIn is not a function",
             "    at Strategy.strategy.success (/usr/app/node_modules/passport/lib/middleware/authenticate.js:247:13)",
             "    at verified (/usr/app/node_modules/passport-oauth2/lib/strategy.js:186:20)",
             "    at processTicksAndRejections (node:internal/process/task_queues:83:21)"
         ],
         "err": null
     }
```
it may only be a typo in the lib in the new version ?

this is my implementation :
```
let FacebookStrategy = require('passport-facebook').Strategy;

        async function facebookConnect(req, accessToken, refreshToken, profile) {
            let user = ...;
            
            return user;
        }

        passport.use(
            new FacebookStrategy(config.facebook, (req, accessToken, refreshToken, profile, callback) => {
                profile = profile._json;

                require('util').callbackify(facebookConnect)(req, accessToken, refreshToken, profile, callback);
            })
        );

        app.get(
            '/auth/facebook',
            passport.authenticate('facebook', {
                authType: 'rerequest',
                scope: ['email', 'public_profile'],
            })
        );

        app.get(
            '/auth/facebook/callback',
            passport.authenticate('facebook', {
                session: false,
                failureRedirect: '/login',
            }),
            (req, res, next) => {
                res.redirect('/');
            }
        );
```

**Comment by xfournet** [comment]
We had a similar problem with `passport-azure-ad-oauth2` after updating to passport 0.5.0
We solved our problem by calling `app.use(passport.initialize())`  before `app.get('...', passport.auhenticate(...))` calls

**Comment by rafipiccolo** [comment]
thanks now it works.
it appears that i was not even calling this line before.
i was relying on a bug this whole time :) or the new version is a breaking change and should have been a major.

have a nice day

**Comment by tylerpope** [comment]
> We had a similar problem with `passport-azure-ad-oauth2` after updating to passport 0.5.0 We solved our problem by calling `app.use(passport.initialize())` before `app.get('...', passport.auhenticate(...))` calls

I totally missed this somehow, this fixed my issue. Thanks!

**Comment by giraffesyo** [comment]
> i was relying on a bug this whole time :) or the new version is a breaking change and should have been a major.

Not sure if passport is following [semver](https://semver.org/) but a good rule of thumb for packages is if it isn't yet version 1 every change should be considered breaking.
