### ISSUE TITLE
Passport function callback doesn't work

### ISSUE THREAD

**Issue by HideakiAtsuyo** [jaredhanson/passport#866]
Hello so i'm trying to log-in and if the password isn't right it's supposed to tell it

```js
passport.authenticate("local", {
        successRedirect: "/chat",
        failureRedirect: "/auth",
        failureFlash: true
      })(req, res, next)
```
work but
```js
passport.authenticate('local', {
          failureRedirect: "/auth",
          failureFlash: true
        }),
        function(req, res) {
            res.redirect('/chat');
        }
```

Just make an infinite loading :)

It doesn't even do anything, even if i add a console.log to check it doesn't use it, also how can i get back the message in the new LocalStrategy to use it with req.flash ? 

* Operating System: Windows
* Node version: 17.1.0
* passport version: ![](https://i.imgur.com/xdWPqaT.png)

**Comment by HideakiAtsuyo** [comment]
By the way when i use the first function it work perfectly and redirect :)

**Comment by jaredhanson** [comment]
You aren't actually passing the function to passport:

```
passport.authenticate('local', {
          failureRedirect: "/auth",
          failureFlash: true
        }), // <-- The `)` closes the `passport.authenticate()` call, so the function below isn't passed as an argument.
        function(req, res) {
            res.redirect('/chat');
        }
```

To fix it, move the closing parenthesis:

```
passport.authenticate('local', {
          failureRedirect: "/auth",
          failureFlash: true
        }, 
        function(req, res) {
            res.redirect('/chat');
        }) // <-- close the function call here
```

**Comment by HideakiAtsuyo** [comment]
```js
passport.authenticate('local', {
        failureRedirect: "/auth",
        failureFlash: true
      }, 
      function(req, res) {
          console.log("Logged in !")
          res.redirect('/chat');
      });
```

Still doesn't work..

[Video Here(ImGur)](https://i.imgur.com/Vn9Sx1J.mp4)

**Comment by HideakiAtsuyo** [comment]
But when it will be solved, how I will have to do to get the message returned by passport(incorrect password etc..) to flash them in `result_message` ?

**Comment by Yanskidoo** [comment]
If you have change your failure flash variable name you have to use type in parameters. 
![flash](https://user-images.githubusercontent.com/93407021/167175993-2f7236b9-ddb1-457c-9257-361bb5d423ee.JPG)
