### ISSUE TITLE
Some strange error after upgrade to the latest version of the package (Salesforce)

### ISSUE THREAD

**Issue by tarakeshp** [jaredhanson/passport#880]
Package: require('passport-forcedotcom').Strategy;

Scopes: id profile email address phone api web full chatter_api visualforce refresh_token offline_access openid custom_permissions wave_api

`The value of the "scope" parameter contains a character that is not allowed or the value exceeds the maximum allowed length. Remove the character from the parameter value or reduce the value length and resubmit. If the error still persists, report it to our Customer Support team. Provide the URL of the page you were requesting as well as any other related information.
`

Need some help here

**Comment by jaredhanson** [comment]
This would be better addressed by filing an issue with the [passport-forcedotcom](https://github.com/joshbirk/passport-forcedotcom) package.

**Comment by jaredhanson** [comment]
One question: are you referring to upgrading that strategy package, or passport itself?  If the latter, does it work on some versions of passport, but not others?  If you can provide details that pinpoint this to an issue in passport, please reopen.  Thanks!
