### ISSUE TITLE
ERROR: SAML provider returned Responder error: undefined

### ISSUE THREAD

**Issue by LeonardoDB** [jaredhanson/passport#888]
Hi everyone

I'm getting this error 'Error: SAML provider returned Error response: undefined' when some users try to send callback to authenticate saml
```js
Error: SAML provider returned Responder error: undefined
    at SAML.validatePostResponseAsync (/opt/node_modules/passport-saml/lib/node-saml/saml.js:637:39)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
Can anyone help me urgently?

### Environment

* Operating System: 
* Node version: 12
* passport-saml: ^3.1.0

**Comment by jaredhanson** [comment]
This question should be posed to the [passport-saml](https://github.com/node-saml/passport-saml) project.
