### ISSUE TITLE
 AuthenticationError is not exported.

### ISSUE THREAD

**Issue by Shubham-Kumar-2000** [jaredhanson/passport#891]
`AuthenticationError` is not exported.

When ever there is a Error occurs while authenticating passport throws a `AuthenticationError` to the express error handler i.e. `next(AuthenticationError)` 
Now if we have a global error handler middleware to handle different types of error differently then we can't do this.
If we export `AuthenticationError` then the users can handle passport errors differently using 

```js
if(err instanceof AuthenticationError){
  // do some thing different
}
```

### Expected behavior
`AuthenticationError` should be exported.

### Actual behavior
 `AuthenticationError` is not exported.

### Environment

* Operating System: *
* Node version: 16.x
* passport version: 0.5.2

**Comment by jaredhanson** [comment]
My recommendation is you check `error.status` rather than `instanceof`.  For example:

```
if(err.status === 401){ // authentication error
  // do some thing different
}
```

Checking `instanceof`can be problematic, since individual strategies may error with instances of classes within their package, which would not satisfy an `instanceof` check.  By checking for `status`, you can handle all authentication related errors, without depending on internals of middleware or strategies.

**Comment by Shubham-Kumar-2000** [comment]
At least Can we have error formatter? @jaredhanson 

Something similar to `serializeUser`

**Comment by jaredhanson** [comment]
Can you describe more what you would expect from a proposed API?  What would it offer that can't be accomplished in middleware?

**Comment by Shubham-Kumar-2000** [comment]
See suppose we want to change the error message / delete the stack trace or any manipulation we want to do with the error.

Then what we have to do is after every `passport` middleware we will have to attach a `passportErrorHandler` i.e

```js
router.get(
    '/github/',
    passport.authenticate('github'),
    passportErrorHandler,
    login
);
router.get(
    '/bitbucket',
    passport.authenticate('bitbucket'),
    passportErrorHandler
    login
);
```

Even this doesn't ensures that the error is from passport only. 
Suppose we have some default middleware just before passport and they throw some error then also it will reach the `passportErrorHandler`.

Thus if we are able to set a `errorFormatter` then it can cover this issue entirely.

@jaredhanson I can raise a PR if you agree.

**Comment by Shubham-Kumar-2000** [comment]
See If I put it in very simple terms how can I exactly know that this particular error is form passport and I need to handle that differently.

Earlier you suggested :
```js
if(err.status === 401){ // authentication error
  // do some thing different
}
```

This doesn't makes sure that the error is from passport only.
@jaredhanson

**Comment by jaredhanson** [comment]
It'll be from passport if that was the middleware preceding the error handler.  For example:

```
router.get(
    '/github/',
    someOtherMiddlewareThatMightDo401Error,
    nonPassportAuthErrorHandler,
    passport.authenticate('github'),
    passportErrorHandler,
    login
);
```

That will let you trap non-passport errors earlier in the stack, if you need.  Express, is quite flexible in this regard.   That being said, this seems like quite an edge case and I am curious as to what other middleware besides passport would be yielding errors with a `401` status that need to be handled in a special manner.
