### ISSUE TITLE
Error: req#logout requires a callback function (regression)

### ISSUE THREAD

**Issue by CherryDT** [jaredhanson/passport#902]
### Expected behavior
`req.logout()` without a callback should work, as it did before and as [your docs](https://www.passportjs.org/concepts/authentication/logout/) show. 

### Actual behavior
Error is thrown: `req#logout requires a callback function`

* passport version: 0.6.0

This bug was introduced four days ago in [this commit](https://github.com/jaredhanson/passport/commit/a77271f55f045bd4fd2578a953256406b3621721#diff-42fef4ca2002dd0838108adc9bb4e5234aa309e7e6efcc5281e78e64c74a289dR59). 

The branch that doesn't use session manager which you added later has `done && done()` as expected but the other one now checks whether `done` is a function and throws if it's not. It should probably also check for existence first.

**Comment by jaredhanson** [comment]
This change is intentional, as described in the release [announcement](https://medium.com/passportjs/fixing-session-fixation-b2b68619c51d).  It is necessary in order to improve the security of how sessions are managed during logout.  Upgrading to 0.6.0 will require applications to pass a callback to `req#logout`.  I'm still working on updating the docs and examples.

**Comment by simonplend** [comment]
The documentation for `req.logout()` needs updating to mention the requirement to pass a callback:

- https://www.passportjs.org/concepts/authentication/logout/
- https://github.com/passport/www.passportjs.org/blob/master/docs/logout.md

I'll see if I get chance to put together a PR for this, but flagging it here in case someone else is able to 😄

**Comment by vlad-healthhelper** [comment]
When I call logout with a call back after upgrading, the request just hangs for me. anything i'm doing wrong? I'm using passport with NestJS

**Comment by DJFriar** [comment]
> The documentation for `req.logout()` needs updating to mention the requirement to pass a callback:
> 
> * https://www.passportjs.org/concepts/authentication/logout/
> * https://github.com/passport/www.passportjs.org/blob/master/docs/logout.md
> 
> I'll see if I get chance to put together a PR for this, but flagging it here in case someone else is able to 😄

So about that documentation.... I keep getting Failed to deserialize errors now and every time I google it this thread comes back up.

**Comment by williamAdson** [comment]
@vlad-healthhelper > When I call logout with a call back after upgrading, the request just hangs for me. anything i'm doing wrong? I'm using passport with NestJS

I don't know if you found the answer yet!
but this worked for me....

router.get('/logout', function(req, res, next){
  if(req.user){
    req.session.destroy();
    res.redirect('/');
  }else{
    res.redirect('/');
  }
});

**Comment by Nditah** [comment]
```js
  app.get('/logout', (req, res) => {
    req.logout(function(err) {
      if (err) { return next(err); }
      return res.redirect('/');
    });
  });
```
