### ISSUE TITLE
Setting a successFlash on passport.authenticate quit working after updating passport to v0.6.0

### ISSUE THREAD

**Issue by dpawson905** [jaredhanson/passport#906]
Before I updated passport to 0.6.0 this worked when a user logged in. 

```JavaScript
passport.authenticate('local', {
      successRedirect: '/',
      failureRedirect: '/',
      successFlash: `Welcome back ${user.username}`,
      failureFlash: true,
    })(req, res, next);
```

Before I updated I was on 0.5.2. Has something changed to prevent this from working? 

Thanks in advance

**Comment by jaredhanson** [comment]
There isn't any known impact to this feature, so any further details or debugging you could provide would help pinpoint the issue.

**Comment by dpawson905** [comment]
I was able to solve it by doing this instead... 

```JavaScript
passport.authenticate('local', {
      successRedirect: '/',
      failureRedirect: '/',
      successFlash: true,
      failureFlash: true,
    });
    req.flash('success', `Welcome back ${user.username}`);
    return res.redirect('/');
```
However, the code from my previous post will work if I downgrade passport back to 0.5.2. I noticed the same thing using passport-google-oauth2 when upgrading to 0.6.0 except it killed flash messages all together. As far as debugging, if I revert the code back to what I had in the first post and i console log req.session it returns an empty object for req.flash

```JavaScript
Session {
  cookie: {
    path: '/',
    _expires: 2022-05-27T03:53:29.506Z,
    originalMaxAge: 3600000,
    httpOnly: true
  },
  flash: {},
  lastModified: 2022-05-27T02:53:29.506Z
}
```

If you need anything else as far as debugging, let me know and I will post it.  

Thanks
