### ISSUE TITLE
Callback is not a function on logout

### ISSUE THREAD

**Issue by phuze** [jaredhanson/passport#913]
I am using the following packages:

- [passport](https://github.com/jaredhanson/passport) `0.6.0`
- [passport-azure-ad](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/maintenance/passport-azure-ad) `4.3.3` (microsoft strategy)
- [@superfaceai/passport-twitter-oauth2](https://github.com/superfaceai/passport-twitter-oauth2) `1.0.0` (twitter strategy)

When including [passport-azure-ad](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/maintenance/passport-azure-ad) as a Microsoft Azure AD strategy, passport throws an error when attempting to log-out of another provider (in this case, twitter):

```
/sandbox/node_modules/passport/lib/sessionmanager.js:90
    cb();
    ^

TypeError: cb is not a function
    at /sandbox/node_modules/passport/lib/sessionmanager.js:90:7
    at Immediate.<anonymous> (/sandbox/node_modules/express-session/session/store.js:54:5)
    at processImmediate (internal/timers.js:464:21)
```

This error happens as of `0.6.0`, and does not appear to be present in `0.5.3`.

I will note that in my example, I have two different logout routes:
- `/logout-microsoft` for Microsoft; their workflow wants you to redirect to their logout page: https://login.microsoftonline.com/common/oauth2/v2.0/logout, which then redirects back to our own app.
- `/logout` for twitter -- the typical Passport logout routine.

### Expected behavior
The user is logged out, without error.

### Actual behavior
The application crashes as a result of the callback error.

### Steps to reproduce
I have reproduced this issue in Codesandbox, using two sandboxes to demonstrate. Note that I have not included any twitter or microsoft related keys, so you can't actually use this demo to sign-in. Though that's not important, as the error can be demonstrated regardless.

1. https://codesandbox.io/s/passport-error-su7tom - This sandbox reproduces the error.
2. https://codesandbox.io/s/passport-error-no-ms-l5zbix - This is a clone of the above sandbox, but with the Microsoft-related code commented out. This is for comparison without the error occuring.

### Environment

* Node version: `16.14.1`
* passport version: `0.6.0`

**Comment by AdrieneTZ** [comment]
I  encountered the same issue while using `logout().`

I am using the following package:
- passport `0.6.0`
- passport-local `1.0.0`

Following the Passport documentation, the part of Log Out, I get the error message "req#logout requires a callback function."
I tried putting `res.redirect('/')` into `req.logout()` as the callback function. It works! 
I tried passport `0.5.3`, and there is no such error message.

**Comment by phuze** [comment]
> Following the Passport documentation, the part of Log Out, I get the error message "req#logout requires a callback function." I tried putting `res.redirect('/')` into `req.logout()` as the callback function. It works! I tried passport `0.5.3`, and there is no such error message.

@AdrieneTZ, that relates to an undocumented change introduced in version `0.6.0`, which was done to address a security vulnerability. The author [wrote](https://github.com/jaredhanson/passport/issues/902#issuecomment-1133897569):

> This change is intentional, as described in the release [announcement](https://medium.com/passportjs/fixing-session-fixation-b2b68619c51d). It is necessary in order to improve the security of how sessions are managed during logout. Upgrading to 0.6.0 will require applications to pass a callback to req#logout. I'm still working on updating the docs and examples.

You must pass a callback function to the `logout()` method, as of `0.6.0`:

```js
//  <= version 0.5.3
req.logout();

//  >= version 0.6.0
req.logout(function(err) => {
  if (err) { return next(err); }
  res.redirect('/');
});
```

**Comment by AdrieneTZ** [comment]
Thank you, @phuze. I am new to programming and using libraries. Your response helped me a lot!

**Comment by jfstephe** [comment]
@jaredhanson -  I'm seeing this too. I think this is a breaking change with the passport-azure-ad plugin again :-(. passport-azure-ad 4.3.3 (the latest) depends on passport 0.4.1 which explodes when req.logout is called with a timeout.

**Comment by wddrosa** [comment]
@phuze I use /```
/  >= version 0.6.0
req.logout(function(err) => {
  if (err) { return next(err); }
  res.redirect('/');
});
```
Still get ` Uncaught TypeError TypeError: cb is not a function` error

**Comment by gleuch** [comment]
@wddrosa Check your strategies' dependencies. They may be requiring older versions of passport that are causing conflicts with the loaded SessionManager.

Not recommended, but if you need a hotfix for a stale strategy, you can try resolving the version of passport used in those strategies using `resolutions` in your `package.json`.

**Comment by jeffwilcox** [comment]
I'm not sure which dependency is causing the problem, but I'm also using `passport-azure-ad`, and while it has a dependency on this latest version of `passport`, something else is bringing in an old version and causing the issue.

**Comment by chriseaton** [comment]
Experiencing this as well, the callback is never called, logout throws the error:
```
req.logout((err) => {
            if (err) {
                return next(err);
            }
            res.redirect(process.env.AUTHENTICATION_LOGOUT_REDIRECT || '/');
        });
```
Results in:

```
node_modules/passport/lib/sessionmanager.js:90
      cb();
      ^
TypeError: cb is not a function
node_modules/passport/lib/sessionmanager.js:90:7
```

**Comment by chriseaton** [comment]
It looks like internally, `req._passport.instance._sm.logOut` is looking for a callback signature of `(req, done)`, but this is not being properly passed from the logout function passport adds to the request.

The current mitigation is to just call it directly yourself and bypass the request wrapper (not a formal/long-term fix), as such:
```
req._passport.instance._sm.logOut(req, (err) => {
            if (err) {
                return next(err);
            }
            res.redirect('/');
        });
```

**Comment by chriseaton** [comment]
Follow-up - this is actually *"fixed"* in passport.
The issue, I discovered, is one of the passport *strategy* packages I was using (in this case, `passport-mock-strategy`) has an old version of passport in their package.json - which it used instead of the latest version.

So the solution, actually, is double-check your strategies are using the same version as you've loaded in throughout.

**Comment by phuze** [comment]
Closing as Microsoft updated their dependency version of Passport from `0.4.1` to `0.6.0` on [Aug 22, 2022](https://github.com/AzureAD/microsoft-authentication-library-for-js/commit/23473d54d9ecbe5a8bb8e7c8ecd3248425b7473e). I abandoned the use of [passport-azure-ad](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/maintenance/passport-azure-ad), so I cannot personally confirm it resolved the issue, though it likely does.
