### ISSUE TITLE
Alleged typo in authenticate middleware

### ISSUE THREAD

**Issue by joaogardenberg** [jaredhanson/passport#920]
https://github.com/jaredhanson/passport/blob/1e8f112bd233dbffb1904d4dd2051780d81b0a22/lib/middleware/authenticate.js#L177

Shouldn't that be `res.send`? I'm getting an error in my app because of that:

![image](https://user-images.githubusercontent.com/6900749/178000304-618feaf0-8999-4c76-aa66-0719b084b7d5.png)

**Comment by jaredhanson** [comment]
It should definitely be `res.end`.  Could you provide more details about your application (which framework, version of node, etc.)
