### ISSUE TITLE
passport.authenticate("local") is not working at all

### ISSUE THREAD

**Issue by Haneesh000** [jaredhanson/passport#921]
when I use passport.authenticate("local") after the login of user and after using passport.authenticate then I go to /auth which sends me back false

After login I use:-
passport.authenticate("local");

In /auth route I use:-
app.get("/auth", (req, res) => {res.send(req.isAuthenticated())});

I am using
"passport": "^0.6.0",
"passport-google-oauth20": "^1.0.0",
"passport-local": "^1.0.0"

This is app is base on node js and express js...

**Comment by jaredhanson** [comment]
Can you run the [todos-express-password](https://github.com/passport/todos-express-password) example application and confirm (or not) that the local strategy is working?  If it is, double check your application and verify that middleware - sessions in particular - are initialized correctly.

**Comment by Haneesh000** [comment]
Hey @jaredhanson but in my app req.isAuthenticated() returns false even if I use passport.authenticate("local")

**Comment by jaredhanson** [comment]
Next steps would be to compare the example app and your app.  Adjust your app accordingly to fix the integration.

**Comment by Haneesh000** [comment]
Okay I'll try that

**Comment by Haneesh000** [comment]
Can you please make a tutorial on how to use passport local strategy in youtube @jaredhanson

**Comment by jaredhanson** [comment]
Is the tutorial on the website not sufficient? https://www.passportjs.org/tutorials/password/

**Comment by Haneesh000** [comment]
No it is a bit difficult to follow it and also there is no method to use passport with other apis than mongoose and mongodb @jaredhanson

**Comment by Haneesh000** [comment]
A youtube video will be better to follow with step-by-step explaination @jaredhanson

**Comment by jaredhanson** [comment]
It's not high on my priority list to make videos, but thanks for the feedback.
