### ISSUE TITLE
Passport 0.4.0 release note required

### ISSUE THREAD

**Issue by bsarankumar** [jaredhanson/passport#953]
Team,

Kindly share the Passport 0.4.0 release note details.

**Comment by bsarankumar** [comment]
Hello team, 
Any updates please. if available release note in portal. kindly let me know the reference details.

**Comment by jaredhanson** [comment]
The changeling is [here](https://github.com/jaredhanson/passport/blob/master/CHANGELOG.md).  Any version not listed there wasn't released with a process that tracked changes.  The changes could be determined by inspecting git history and retroactively added, but that is not a priority for me.
