### ISSUE TITLE
The authentication middleware deletes the data that were inside the session before authentication,  verssion 0.6.0

### ISSUE THREAD

**Issue by rafikchb** [jaredhanson/passport#973]
The authentication middleware deletes the data that were inside the session before authentication in version 0.6.0
### use case . 
When a user tries to access a route that is only accessible by authenticated users, I save the link of the page the user was trying to access in the session. Then, I redirect the user to the login page. After the user submits their credentials, I authenticate the user and redirect them to the URL they were trying to access before they got redirected to the login page, which is normally saved in the session. However, in version 0.6.0 of Passport, the URL saved in the session is being deleted after the user is authenticated.

### Expected behavior
The data saved in the session should be present after the authentication process.

### Actual behavior
The data contained in the session gets deleted after authentication.

### Steps to reproduce
1. create a route that add some data to the session .
```js
router.post("/addDataToSession" , (req,res)=>{
req.session.someData ="some data" ; 
res.send("some data added to the session") ; 
}); 
```
2. add the following route 
```js
router.post("/login",
(req,res, next)=>{ console.log(req.session); next();} , 
 passport.authenticate("local", { failureFlash: true, failureRedirect: "/login" }), (req, res) => {
    const redirectUrl = req.session.returnTo || "/home";
    delete req.session.returnTo ; 
    res.redirect(redirectUrl);
});
```
3. visit the /addDataToSession then , visit then make a post request with the username and password in the body .

### Environment

* Operating System: windows
* Node version: v18.9.0

**Comment by CapCap** [comment]
Same problem- was able to workaround it with the following

```
router.get('/auth/google/callback',
  async (req, res, next) => {
    const redirectUrl: string = (req.session as any).afterLogin;
    await passport.authenticate('google', {})(req, res, next);
    res.redirect(redirectUrl);
    next();
  });
  ```

**Comment by rafikchb** [comment]
The solution is to pass the option **keepSessionInfo: true** to the authenticate method.
