### ISSUE TITLE
Own session data is overwritten by passport

### ISSUE THREAD

**Issue by flyon** [jaredhanson/passport#981]
I was using `express-session` already to store app related things in a session.
Now I've added passport for google OAuth support which works, but when passport stores the user in the session all my other session data is lost. 

Is this intended behaviour? Anyway to keep the old session data?

### Expected behavior
my own session data persists even when using passport

### Actual behavior
session data is cleared and only passport related session data is present

**Comment by flyon** [comment]
Code setup

```
//setup own session
server.use(
      session({
        secret: secret,
        resave: false,
        saveUninitialized: false,
      }),
    );
     
//setup passport    
server.use(passport.initialize());
server.use(passport.session());

//some request before login
request.session.myOwnCustomData = true;
request.session.save(function (err) {
          if (err) return request.next(err);
});

//after passport google oauth login, with google strategy etc, this logs undefined
console.log(request.session.myOwnCustomData);

**Comment by tin-snowflake** [comment]
Got the same error. Did you solve it @flyon?

**Comment by flyon** [comment]
No, not yet, i ended up just using passport for now, replacing the functionality i had built elsewhere. It may become an issue again though if i need to do other things with sessions, not sure

**Comment by bradydoll** [comment]
When you call `passport.authenticate()`, you need to pass `keepSessionInfo: true` in the `AuthenticateOptions` object.

Example:
```
passport.authenticate('authProvider', { keepSessionInfo: true });
```

**Comment by flyon** [comment]
I see! perfect, thank you.

This should probably be added to the sessions documentation page though? https://www.passportjs.org/concepts/authentication/sessions/

There is no mention of this option anywhere otherwise I believe?
